import Ekow from "./images/tom.png"
import Joel from "./images/Image-1.png"
import Nat from "./images/Image-2.png"
import Jerry from "./images/jerry.png"


const people = [
    {
        id: 1,
        pic: Ekow,
        name: 'Ekow Thompson',
        testimony: 'Dosh insurance company prioritizes customer satisfaction and is committed to providing exceptional service to our clients.'
    },
    {
        id: 2,
        pic: Joel,
        name: 'Frank Kay',
        testimony: 'Dosh insurance company prioritizes customer satisfaction and is committed to providing exceptional service to our clients.'

    },
    {
        id: 3,
        pic: Nat,
        name: 'Joel Nettey',
        testimony: `DOSH allows me to pay friends and family without any fees. It's a hassle-free way to transfer money while saving on charges. Thanks to DOSH, I can easily reimburse and support loved ones without worrying about additional costs.`
    },
    {
        id: 4,
        pic: Jerry,
        name: 'Jerry Sam',
        testimony: `DOSH insurance has been a game-changer for me. Their seamless claims process and comprehensive coverage gave me peace of mind. I've saved significantly on my premiums without compromising on quality. The customer service is top-notch, always ready to assist promptly. Choosing DOSH was one of the best decisions I made for my insurance needs.`
    },
]
export default people;

// data.js
export const hospitalData = {
    "Greater Accra": [
        { name: "The Bank Hospital", location: "Cantonment" },
        { name: "Eden Family Hospital", location: "North kaneshie" },
        { name: "Trust Hospital", location: "Osu" },
        { name: "Maritime Hospital", location: "Tema" },
        { name: "Yeboah Hospital", location: "East legon" },
        { name: "Baiden Ghartey Memorial Hospital", location: "Ring Rd Central" },
        { name: "Esidem Hospital", location: "6th Ave, Accra" },
        { name: "The Community Hospital New Ashongman", location: "Kwabenya" },
        { name: "Aneeja Surgical & Medical Hospital", location: "Thyme, Avenue, Accra (Tantra hill)" },
        { name: "Midway Hospital", location: "Tetteh Ashong street" },
        { name: "Afrah Int Hospital", location: "Asylum Down" },
        { name: "Mother Love Hospital", location: "Adenta" },
        { name: "Bengali Hospital", location: "Tema" },
        { name: "Sakumono Community Hospital", location: "Sakumono" },
        { name: "Jubail Hospital", location: "Sakumono" },
        { name: "Accra Ridge Hospital", location: "Ridge" },
        { name: "Tema General Hospital", location: "Tema" },
        { name: "Airport Women Hospital", location: "Airport Residential" },
        { name: "Korle Bu Teaching Hospital", location: "Korlebu" },
        { name: "Oak Specialist hospital", location: "Ashongman" },
        { name: "Lekma Hospital", location: "Teshie" },
        { name: "Claron Health International", location: "Airport Residential" },
        { name: "Lapaz Community Hospital", location: "Lapaz" },
        { name: "Grace Anchor Hospital", location: "Nsawam" },
        { name: "Bemuah Royal Hospital", location: "East Legon" },
        { name: "SDA Hospital Gbawe", location: "Gbawe" },
        { name: "Mab International Hospital", location: "Lapaz" },
        { name: "Afrah International Hospital", location: "Asylum Down" },
        { name: "Tantra Community Hospital", location: "Tantra" },
        { name: "Bether Sp. Hospital", location: "Tema" },
        { name: "Ada East District Hospital", location: "Ada" },
        { name: "Achimota Hospital", location: "Achimota" },
        { name: "Seventh-Day Adventist Hospital, Gbawe", location: "Accra" },
        { name: "Achimota Hospital", location: "Achimota" },
        { name: "New Crystal Hospital", location: "Ashaiman" },
        { name: "New Crystal Hospital", location: "Tema Com 8" },
        { name: "New Crystal Hospital", location: "Afenyo" },
        { name: "New Crystal Hospital", location: "Adjei Kojo" },
        { name: "Hag Hospital", location: "Greater Accra" },
        { name: "Healthnet", location: "Airport Residential" },
        { name: "Accra Medical Centre", location: "Ridge" },
        { name: "University of Ghana Medical Center", location: "Legon" },
        { name: "Nyaho Medical Centre", location: "Airport Residential" },
        { name: "Unimed Hospital Limited", location: "Ofankor Barrier" },
        { name: "Lena Health Service Limited", location: "Accra" },
        { name: "Synlab", location: "Airport Residential" },
        { name: "Quantum Total Wellness Centre", location: "Dansoman" },
        { name: "New Market Health Centre", location: "Kasoa" },
        { name: "Sunshine Diagnostic Center", location: "Airport Residential" },
        { name: "Halleman Medical Services", location: "Atomic Roundabout" },
        { name: "Euracare", location: "Greater Accra" },
        { name: "Nova Wellness Center", location: "Greater Accra" },
        { name: "Global Med Rehab", location: "Kwabenya" },
        { name: "Cassi Medical & Diagnostics Centre", location: "Airport" },
        { name: "Mab Medical Center", location: "Ablekuma" },
        { name: "Elite Care Medical Centre", location: "East Legon" },
        { name: "The Diagnostic Centre", location: "East Legon" },
        { name: "Three Mc Ghana Limited", location: "Accra" },
        { name: "Best Heart Medical Centre Limited", location: "Amasaman" },
        { name: "Sherperdcare Medical Centre", location: "Tema" },
        { name: "Ark Medical Centre", location: "Lapaz" },
        { name: "Mab Medical Center", location: "Darkuman" },
        { name: "The Diagnostic Centre", location: "East Legon" },
        { name: "Blue Valley Specialist", location: "Gbawe" },
        { name: "Tantra Community Clinic", location: "Tantra" },
        { name: "Natural Way Herbal Clinic", location: "Kwashieman" },
        { name: "Rinat Clinic", location: "East Legon" },
        { name: "Lakeside Clinic", location: "Lakeside" },
        { name: "Blessings Clinic Ltd", location: "Abeka Road" },
        { name: "Sandford World Clinic", location: "Adenta" },
        { name: "Theresa Clinic", location: "Orgle Road" },
        { name: "Efan Victory Clinic", location: "Batsonaa Highway" },
        { name: "Medcare Plus Clinic", location: "Accra" },
        { name: "Dansoman Polyclinic", location: "Dansoman" },
        { name: "Civil Service Polyclinic", location: "Accra" },
        { name: "Ogbojo Polyclinic", location: "Ogbojo" },
        { name: "Anyaa Polyclinic", location: "Anyaa" },
        { name: "Tema Polyclinic", location: "Tema" },
        { name: "Civil Service Clinic", location: "Accra Central" },
        { name: "St. Lukes Clinic", location: "Airport Residential" },
        { name: "Prampram Polyclinic", location: "Prampram" },
        { name: "Kaneshie Polyclinic", location: "Kaneshie" },
        { name: "Rabito Clinic", location: "Tema Comm25" },
        { name: "Rabito Clinic", location: "Dansoman" },
        { name: "Rabito Clinic", location: "East Legon" },
        { name: "Rabito Clinic", location: "Kasoa" },
        { name: "Rabito Clinic", location: "Tema C11" },
        { name: "Rabito Clinic", location: "Osu" },
        { name: "Rabito Clinic", location: "Lapaz" },
        { name: "Rabito Clinic", location: "Cosmetic Centre" },
        { name: "Rabito Clinic", location: "Dome" },
        { name: "Rabito Clinic", location: "Kessiman" },
        { name: "Oracare Dental Clinic", location: "Adenta" },
        { name: "Jacob Dental Clinic", location: "East Legon" },
        { name: "Marks Dental Clinic", location: "Ridge" },
        { name: "Gilead Medical & Dental Centre", location: "Asylum Down" },
        { name: "Save The Nations Sight Eye Clinic", location: "East Legon" },
        { name: "Delcielo Optical Services", location: "Ring Road" },
        { name: "Innus Eye & Vision Care Centre", location: "Haatso" },
        { name: "My Eyes Center", location: "East Legon" },
        { name: "Eye Express Limited", location: "Ridge" },
        { name: "Permeff Eye Care", location: "Upsa" },
        { name: "Amasha Partners Optical", location: "Spintex" },
        { name: "Solar Eye Center", location: "" },
        { name: "IRIS Optometric", location: "Korle Bu Road" },
        { name: "Third Eye And Vision Centre Limited", location: "Airport Residential/ North Ridge" },
        { name: "Emmanuel Eye Centre", location: "East Legon" },
        { name: "Save The Nations Sight Eye Clinic", location: "East Legon" },
        { name: "Godly Favoured Eye Care Centre", location: "Lapaz" },
        { name: "Top Up Pharmacy Limited (Adabraka)", location: "Adabraka" },
        { name: "Top Up Pharmacy Limited (Osu)", location: "Osu" },
        { name: "Top Up Pharmacy Limited (Airport Resid.)", location: "Airport Residential" },
        { name: "Top Up Pharmacy Limited (Airport Hills)", location: "Airport Hills" },
        { name: "Top Up Pharmacy Limited (East Legon)", location: "East Legon" },
        { name: "Add Pharmacy Gh Ltd (Bukom Branch)", location: "Bukom Branch" },
        { name: "Add Pharmacy Gh Ltd (Darkuman Total Brach)", location: "Darkuman Total Brach" },
        { name: "Add Pharma (Idustrial Area)", location: "Idustrial Area" },
        { name: "Add Pharma (Asylum Down)", location: "Asylum Down" },
        { name: "Add Pharmacy Gh Ltd (Tseddo Branch)", location: "Tseddo Branch" },
        { name: "Add Pharmacy Gh Ltd (North Ridge Area)", location: "North Ridge Area" },
        { name: "Add Pharmacy Gh Ltd (Pigfarm Total Branch)", location: "Pigfarm Total Branch" },
        { name: "Add Pharmacy Gh Ltd (Movenpick Hotel Branch)", location: "Movenpick Hotel Branch" },
        { name: "Obm Pharmacy ", location: "Tema" },
        { name: "Ernest May Chemist", location: "Odorkor" },
        { name: "Zoe pharmacy (Asylum Down)", location: "Haatso" },
    ],
    "Ashanti": [
        { name: "Kuntanase Government Hospital", location: "Kuntanase" },
        { name: "Gary Marvin Memorial Hospital", location: "Kotwi" },
        { name: "Trinity Health Hospital", location: "Paraku Estate" },
        { name: "Juaso District Hospital", location: "Juaso" },
        { name: "Kokofu General Hospital", location: "Kokofu" },
        { name: "Asonomaso Government Hospital", location: "Asonomaso" },
        { name: "Adansi North District Hospital", location: "Fomena" },
        { name: "True Vine Hospital", location: "Kumasi" },
        { name: "Akropong Government Hospital", location: "Akropon" },
        { name: "Agona Government Hospital", location: "Agona" },
        { name: "Ahafo Ano North Municipal Hospital", location: "Ahafo Ano North" },
        { name: "Obuasi Government Hospital", location: "Obuasi" },
        { name: "New Edubiase Government Hospital", location: "New Edubiase" },
        { name: "Mankranso Government Hospital", location: "Tepa Rd,Mankranso" },
        { name: "Ejura Municipal Hospital", location: "Atebubu-Ejura Rd,Ejura" },
        { name: "Nyinahin Government Hospital A/R", location: "Nyanahin" },
        { name: "Konongo Hospital", location: "Konongo" },
        { name: "Firstcare Hospital", location: "Anane Avenue" },
        { name: "Ausbury Hospital", location: "Anwomaso Rd" },
        { name: "Afari Community Hospital Limited", location: "Nkawie Rd" },
        { name: "A1 Hospital", location: "Bekwai Rd" },
        { name: "Pima Hospital Limited", location: "Tafo" },
        { name: "True Vine Hospital", location: "Kiddwa Kannin st" },
        { name: "St Jude Hospital", location: "Obuasi" },
        { name: "Obuasi Ridge Hospital", location: "Obuasi" },
        { name: "Bryant Mission Hospital", location: "Obuasi" },
        { name: "Tafo Government Hospital", location: "Akyem Kukurantumi" },
        { name: "Effiduase Government Hospital", location: "Effiduase" },
        { name: "Nkawie Toase Govt Hospital", location: "Nkawie Rd, Toase" },
        { name: "Nkenkaasu Government Hospital", location: "Nkenkaasu" },
        { name: "Mamponteng Hospital", location: "Kumasi" },
        { name: "Mampong Municipal Hospital", location: "Mampong" },
        { name: "Juaben Hospital", location: "Juaben" },
        { name: "Elisu Government Hospital", location: "" },
        { name: "A1 Hospital", location: "Bekwai Rd, Kumasi" },
        { name: "Manhyia District Hospital", location: "Zongo Rd,Kumasi" },
        { name: "Bekwai Municipal Hospital", location: "Bekwai" },
        { name: "Sekyedumase Government Hospital", location: "Sekyedumase" },
        { name: "Bechem Government Hospital", location: "Kumasi" },
        { name: "Afariafari Community Hospital", location: "Nkawie Rd, Kumasi" },
        { name: "Obuasi Diagnostic Centre", location: "Obuasi" },
        { name: "Afranoho Health Centre", location: "Kumasi" },
        { name: "Fiappe Health Centre", location: "Odumase" },
        { name: "Akrofuom Health Centre", location: "Amankyim" },
        { name: "Adubia Health Centre", location: "Manso, Adubia" },
        { name: "Akumadan Health Centre", location: "Akumadan" },
        { name: "Brofoyedru Health Centre", location: "Brofoyedru,Buoho,Kumasi" },
        { name: "Beposo Health Centre", location: "Beposo" },
        { name: "Adidwan Health Centre", location: "Adidwan" },
        { name: "Asokwa Health Centre", location: "Fomena" },
        { name: "Ayeduase Health Centre", location: "Kumasi" },
        { name: "Offinso Health Centre", location: "Sraha" },
        { name: "Government Health Centre Ahenkro", location: "Ahenkro" },
        { name: "Pokukrom Health Centre", location: "Fawaman" },
        { name: "Kwanwoma Health Centre", location: "Kumasi" },
        { name: "Assin Manso Health Centre", location: "Assin Manso" },
        { name: "Aboaso Health Centre", location: "Ejura-Kumasi Rd, Aboaso" },
        { name: "Ahenema Kokoben Health Centre", location: "Kumasi" },
        { name: "Jamasi Health Centre", location: "Gyamese" },
        { name: "Jachie Health Centre", location: "Pramso" },
        { name: "Asiwa Health Centre", location: "Asiwa" },
        { name: "Prima Medical Centre", location: "Kumasi" },
        { name: "Rabito Clinic", location: "Lindador Pharmacy" },
        { name: "Drobonso RCH Clinic", location: "Drabondo" },
        { name: "Bomso Clinic", location: "Bomso Crescent" },
        { name: "Rabito Clinic", location: "111 Melcom Rd,Kumasi." },
        { name: "Manso Nkwanta Polyclinic", location: "Manso Nkwanta" },
        { name: "Kumawu Polyclinic", location: "Kumawu" },
        { name: "Afranoho polyclinic", location: "Kumasi" },
        { name: "Abuakwa Polyclinic", location: "Kumasi" },
        { name: "Asuofua Polyclinic", location: "Kumasi" },
        { name: "Quality Health Care", location: "Wesleyan Rd" },
        { name: "Makenzi Health Services", location: "Ahinsan Estate" },
        { name: "Briteaid", location: "Osei tutu Ave" },
        { name: "Prima Medical Centre", location: "Paraku Estate,Kumasi" },
        { name: "Bandy Chemist", location: "Adum Road" },
        { name: "Saqs Pharmacy", location: "Kumasi" },
        { name: "Greenlight Pharmacy", location: "Kumasi" },
        { name: "Rapheka Pharmacy Limited", location: "Kumasi" },
        { name: "Estel Pharmacy", location: "Akrokerri Rd, Obuasi" },
        { name: "Bandy Chemist", location: "Adum-Ashanti" },
        { name: "Bellview Eye Care", location: "Obuase" }
    ],
    "Western": [
        { name: 'Effia-Nkwanta Regional hospital', location: 'J.De Graft-Johnson Ave, Takoradi' },
        { name: 'Nagel Memorial SDA Hospital', location: 'Takoradi' },
        { name: 'Effia-Nkwanta Regional hospital', location: 'J.De Graft-Johnson Ave, Takoradi' },
        { name: 'Essikado Hospital', location: 'Takoradi' },
        { name: 'Efia Nkwanta Hospital', location: 'J.De Graft-Johnson Ave, Takoradi' },
        { name: 'Nagel Memorial SDA Hospital', location: 'Takoradi' },
        { name: 'St. Benedict Hospital', location: 'Inchaban, Sekondi-Takoradi' },
        { name: 'Qui-Wal Hospital', location: 'Takoradi' },
        { name: 'Bethel Methodist Medical Centre', location: '5 Pakos Ave, Takoradi' },
        { name: 'Westview Medicare Centre', location: 'Takoradi' },
        { name: 'New Crystal Medical Centre', location: '3 Coker Ave, Takoradi' },
        { name: 'Afful Lifeline Med.Centre', location: 'Shama Rd, Shama' },
        { name: 'Agona Nkwanta Polyclinic', location: 'Ahanta District' },
        { name: 'Rabito Clinic', location: 'Takoradi' },
        { name: 'Takoradi Dis Clinic', location: 'Takoradi' },
        { name: 'Twin City Clinic', location: 'Takoradi' },
        { name: 'Takoradi High Street Clinic', location: 'Takoradi' },
        { name: 'St. Paul Dental Clinic', location: 'Columbia Ave, Takoradi' },
        { name: 'UQ Specialist Medical Services', location: 'Dial Lane, Takoradi' },
        { name: 'PH Laboratory services', location: 'Fijai, Sekondi, Takoradi' },
        { name: 'Doctors In Service', location: 'Takoradi' },
        { name: 'A Life Line Medical', location: 'Shama Rd, Shama' },
        { name: 'Oasis Medicare Consult', location: 'Takoradi' },
        { name: 'Imperial Eye Care', location: 'West Fijai Near Skyy Power FM Sekondi, Takoradi' },
        { name: 'Uretope Eye Care', location: '21 New John Sarbah Road, Takoradi' },
        { name: 'Delcielo Optician', location: 'Liberation Rd, Takoradi' },
        { name: 'Andrew Amihere-Quarm Vision', location: '21 New John Sarbah Road, Takoradi' },
        { name: 'Vision Crafters 23', location: 'J.De Graft-Johnson Ave, Takoradi' },
        { name: 'Vision Crafters', location: 'Harbour Area, no.18 J. Degrat Johnson Ave' },
        { name: 'Solar Eye Center', location: 'Stc, Takoradi' },
        { name: 'Rapheka Pharmacy', location: 'Columbia, Takoradi' },
        { name: 'Abuakwa Pharmacy', location: 'Takoradi' },
        { name: 'Kabmore Pharmacy', location: 'Takoradi' },
        { name: 'Atlantic Chemist', location: 'Shippers Council Road, Takoradi' },
        { name: 'Adombi Dental', location: '14/4 No, 28 Liberation Rd, Takoradi' }
    ],
    "Volta": [
        { name: 'Mater Ecclesaie Hospital', location: 'Sokode' },
        { name: 'Catholic Hospital Battor', location: 'Battor' },
        { name: 'Margret Marquart Hospital', location: 'Kpando' },
        { name: 'Ho Teaching Hospital', location: 'Ho-Denu Rd, Ho' },
        { name: 'Anfoega Catholic Hospital', location: '818 Derby Ave, Accra' },
        { name: 'Volta Regional Hospital', location: 'Ho' },
        { name: 'Ho Royal Hospital Limited', location: 'Ho' },
        { name: 'Keta Municipal Hospital', location: 'Norlivime Link, Keta' },
        { name: 'Peki Government Hospital', location: 'Peki' },
        { name: 'Ho Royal Hospital Limited', location: 'Ho' },
        { name: 'Anfoega Catholic Hospital', location: 'Derby Ave, Accra' },
        { name: 'Cederville hospital', location: 'Hohoe' },
        { name: 'Mary Theresa Hospital', location: 'Dodi Papase' },
        { name: 'Volta Regional Hospital', location: 'Ho' },
        { name: 'Worawora Government hospital', location: 'Nkwanta-Kpando Rd, Worawora' },
        { name: 'Foresight Medical Centre', location: 'Ho' },
        { name: 'Rabito Clinic', location: 'Aflao' },
        { name: 'Rabito Clinic', location: 'Ho' }
    ],
    'Bono': [
        { name: 'Kintampo South District Hospital', location: 'Kintampo' },
        { name: 'Kintampo Municipal Hospital', location: 'Kintampo' },
        { name: 'Sampa Government Hospital', location: 'Sampa' },
        { name: 'Tain District Hospital, Nsawkaw', location: 'Nsawkaw' },
        { name: 'Kwatire Hospital', location: 'Odumase' },
        { name: 'Sena West District Hospital', location: 'Sena East' },
        { name: 'Dormaa East District Hospital', location: 'Wamfie' },
        { name: 'Wenchi Health Centre', location: 'Wenchi' },
        { name: 'Banda Nhenkro Health Centre', location: 'Banda Nhenkro (Bono)' },
        { name: 'Jinijini Health Centre', location: 'Jinijini' },
        { name: 'Prang Health Centre', location: 'Prang' },
        { name: 'Nkoranza Health Centre', location: 'Nkoranza' },
        { name: 'Fiappe Health Centre', location: 'Odumase' },
        { name: 'Drobo Polyclinic', location: 'Brobo' },
        { name: 'Nsoatre Polyclinic', location: 'Odumase' },
        { name: 'Worae Care Clinic', location: '' },
        { name: 'CHIRAA', location: 'Chira' },
        { name: 'Busunya Polyclinic', location: 'Busunya' }
    ],
    "Ahafo": [
        { name: 'Techimantia Government Hospital', location: 'Techiman' },
        { name: 'Asunafo South District Hospital', location: 'Goase' },
        { name: 'Bibiani Municipal Hospital', location: 'Bibiani' },
        { name: 'Kukuom District Hospital', location: 'Asunafo South District' },
        { name: 'Goaso Municipal Government Hospital', location: 'Goase' },
        { name: 'St Elizabeth Catholic Hospital', location: 'Hwidiem' },
        { name: 'Kenyasi District Hospital', location: 'Asutifi North' },
        { name: 'Techimantia Government Hospital', location: 'Techiman' },
        { name: 'Banhart Hospital', location: 'Asutifi North' },
        { name: 'Bechem Government Hospital', location: 'Sunyani' },
        { name: 'Health Point Hospital', location: '' },
        { name: 'Holy Family Hospital', location: 'Techiman-Tamale Road, Techiman' },
        { name: 'Sunyani Municipal Hospital', location: 'Sunyani-Wenchi Rd, Sunyani' },
        { name: 'Bono Regional Hospital', location: 'Sunyani-Wenchi Rd, Sunyani' },
        { name: 'Abrafi Women And Children Hospital', location: 'AN1 Nana Dwamena St, Techiman' },
        { name: 'Nsoatre Health Centre', location: 'Nsuatre' },
        { name: 'Tuobodom Health Centre', location: 'Tuobodom' },
        { name: 'Mim Health Center', location: 'Mim' },
        { name: 'Aspire Clinic and Maternity Home', location: 'Sunyani' },
        { name: 'Divine Star Clinic and Maternity', location: '' },
        { name: 'Aspire Clinic And Maternity Home', location: 'Off Techiman Rd, Kotokrom Aviation, Sunyani' },
        { name: 'Rabito Clinic', location: 'Sunyani' },
        { name: 'Chiraa', location: 'Sunyani' },
        { name: 'Medcourt Pharmacy', location: 'Bechem' }
    ],
    "Eastern": [
        { name: 'Tetteh Quashie Memorial Hospital', location: 'Mampong' },
        { name: 'Kade Government Hospital', location: 'Kade' },
        { name: 'Oda Government Hospital', location: 'Koforidua' },
        { name: 'Nsawam Government Hospital', location: 'Nsawam' },
        { name: 'SDA Hospital', location: 'Koforidua' },
        { name: 'Divine Victory Hospital', location: 'Akim, Oda' },
        { name: 'Nsawam Government Hospital', location: 'Nsawam' },
        { name: 'Enyirese Municipal Hospital', location: 'Akyem, Enyiresi' },
        { name: 'Kenop Hospital Care', location: 'Nkwakaw' },
        { name: 'Suhum Government Hospital', location: 'Suhum' },
        { name: 'Akim Oda Government Hospital', location: '9 Kade-Brofoyedru Rd, Akim Oda' },
        { name: 'Asamankese Government Hospital', location: 'Asamankese' },
        { name: 'Holy Family Hospital', location: 'Nkwakaw' },
        { name: 'Suhum Government Hospital', location: 'Suhum' },
        { name: 'Kade Government Hospital', location: 'Kade' },
        { name: 'Eastern Regional Hospital', location: 'Koforidua' },
        { name: 'St. Johns Hospital And Fertility Centre', location: 'Nsawam' },
        { name: 'Newlands Medical Centre', location: 'Koforidua' },
        { name: 'Rabito Clinic', location: 'Koforidua' },
        { name: 'Catholic Community & Maternity Clinic', location: 'Akim, Swedru' },
        { name: 'Jacob Dental Clinic', location: 'Akwapim South' },
        { name: 'Rabito Clinic', location: 'Adiebera-Kumasi' },
        { name: 'St. John Polyclinic', location: '' }
    ],
    "Oti": [
        { name: 'Nkwanta Municipal Hospital', location: 'Nkwanta' },
        { name: 'Worawora Government Hospital', location: 'Kadjebi' },
        { name: 'Nkwanta Municipal Hospital', location: 'Nkwanta' },
        { name: 'Krachi Municipal Hospital', location: 'Kyinderi' },
        { name: 'Chinderi Health Centre', location: 'Kyinderi' },
        { name: 'Kadjebi Health Centre', location: 'Kadjebi' },
        { name: 'St. Lukes Clinic', location: 'Senchi Street' }
    ],
    "Northern": [
        { name: 'Tamale West Hospital', location: 'Tamale' },
        { name: 'Tamale SDA Hospital', location: 'Salaga Rd, Tamale' },
        { name: 'Tamale Teaching Hospital', location: 'Tamale' },
        { name: 'Tatale District Hospital', location: 'Tamale' },
        { name: 'Bimbilla Municipal Hospital', location: 'Bimbilla' },
        { name: 'Zamzugu District Hospital', location: 'Zamzugu' },
        { name: 'Yendi Municipal Hospital', location: 'Yendi' },
        { name: 'Kintampo South District Hospital', location: 'Jema' },
        { name: 'Gushegu Municipal Hospital', location: 'Yendi-Gushiegu Rd.' },
        { name: 'Tolon District Hospital', location: 'Tamale-Tolon Rd.' },
        { name: 'Northern Regional Hospital', location: 'Tamale' },
        { name: 'Karaga District Hospital', location: 'Karaga' },
        { name: 'Kpandai District Hospital', location: 'Kpandai' },
        { name: 'Nanton Health Centre', location: 'Nanton' },
        { name: 'Saboba Health Centre', location: 'Saboba' },
        { name: 'Sang Health Centre', location: 'Sang' },
        { name: 'Choggu Health Centre', location: 'Tamale' },
        { name: 'Kumbumgu Health Centre', location: 'Tamale' },
        { name: 'Rabito Clinic', location: 'Tamale' }
    ],
    "Upper West": [
        { name: 'Rabito Clinic', location: 'Upper West Wa' },
        { name: 'Jirapa Urban Health', location: 'Upper West Wa' }
    ],
    "Upper East": [
        { name: 'Rabito Clinic', location: 'Upper East Bolgatanga' },
    ],
    "Savannah": [
        { name: 'Daboya Health Centre', location: 'Savannah	Damongo' },
        { name: 'Buipe Health Centre', location: 'Savannah	N10, Buipe' }
    ],




}
