import Ekow from "./images/tom.png"
import Joel from "./images/Image-1.png"
import Nat from "./images/Image-2.png"
import Jerry from "./images/jerry.png"


const people = [
    {
        id: 1,
        pic: Ekow,
        name: 'Ekow Thompson',
        testimony: 'Dosh insurance company prioritizes customer satisfaction and is committed to providing exceptional service to our clients.'
    },
    {
        id: 2,
        pic: Joel,
        name: 'Frank Kay',
        testimony: 'Dosh insurance company prioritizes customer satisfaction and is committed to providing exceptional service to our clients.'

    },
    {
        id: 3,
        pic: Nat,
        name: 'Joel Nettey',
        testimony: `DOSH allows me to pay friends and family without any fees. It's a hassle-free way to transfer money while saving on charges. Thanks to DOSH, I can easily reimburse and support loved ones without worrying about additional costs.`
    },
    {
        id: 4,
        pic: Jerry,
        name: 'Jerry Sam',
        testimony: `DOSH insurance has been a game-changer for me. Their seamless claims process and comprehensive coverage gave me peace of mind. I've saved significantly on my premiums without compromising on quality. The customer service is top-notch, always ready to assist promptly. Choosing DOSH was one of the best decisions I made for my insurance needs.`
    },
]
export default people;

// data.js
export const hospitalData = {
    "Greater Accra": [
        { name: "The Bank Hospital", regionName: "Greater Accra", location: "Cantonment", contactNumber: "0302739373", email: "info@thebankhospital.com" },
        { name: "Eden Family Hospital", regionName: "Greater Accra", location: "North kaneshie", contactNumber: "0302224984", email: "" },
        { name: "Trust Hospital", regionName: "Greater Accra", location: "Osu", contactNumber: "0302761974/0302761975", email: "info@thetrusthospital.com" },
        { name: "Tema Regional Maritime Hospital", regionName: "Greater Accra", location: "Tema", contactNumber: "0303220030", email: "info@imah.com.gh" },
        { name: "Baiden Ghartey Memorial Hospital", regionName: "Greater Accra", location: "Ring Rd Central", contactNumber: "0506665760", email: "baidengharteyhospital@gmail.com" },
        { name: "Esidem Hospital", regionName: "Greater Accra", location: "6th Ave, Accra", contactNumber: "0302520345", email: "esidemhospital.org@gmail.com" },
        { name: "Aneeja Surgical & Medical Hospital", regionName: "Greater Accra", location: "Thyme, Avenue,Accra(Tantra hill)", contactNumber: "0302411491", email: "administration@aneeja-hospital.com" },
        { name: "Midway Hospital", regionName: "Greater Accra", location: "Tetteh Ashong street", contactNumber: "0548348900/0302950173", email: "info@midwayclinicgh.com" },
        { name: "Afrah Int Hospital", regionName: "Greater Accra", location: "Aslyum Down", contactNumber: "0302267151/0557518126", email: "afrahinternationalhospital@gmail.com" },
        { name: "Mother Love Hospital", regionName: "Greater Accra", location: "Adenta", contactNumber: "0201424011", email: "motherlovehospital@gmail.com" },
        { name: "Bengali Hospital", regionName: "Greater Accra", location: "Tema", contactNumber: "0206301354", email: "" },
        { name: "Sakumono Community Hospital", regionName: "Greater Accra", location: "Sakumono", contactNumber: "0303403515", email: "sakumonocommunityhospital.org" },
        { name: "Jubail Hospital", regionName: "Greater Accra", location: "Sakumono", contactNumber: "0303401167/030401403/0508743886", email: "info@jubailhospital.com" },
        { name: "Accra Ridge Hospital", regionName: "Greater Accra", location: "Ridge", contactNumber: "0247814770/0302428460", email: "info@garh.gov.gh" },
        { name: "Tema General Hospital", regionName: "Greater Accra", location: "Tema", contactNumber: "0303302695", email: "temageneralhospital2017@gmail.com" },
        { name: "Airport Women Hospital", regionName: "Greater Accra", location: "Airport Residential", contactNumber: "0302736107", email: "info@airportwomenshospital.com" },
        { name: "Korle Bu Teaching Hospital", regionName: "Greater Accra", location: "Korlebu", contactNumber: "0302739510/0243407809", email: "info@kbth.gov.gh" },
        { name: "Oak Specialist hospital", regionName: "Greater Accra", location: "Ashongman", contactNumber: "0509760659/0599642520", email: "info@oakspecialisthospital.com" },
        { name: "Lekma Hospital", regionName: "Greater Accra", location: "Teshie", contactNumber: "0207826608/0302717945", email: "lekmahospital12@gmail.com" },
        { name: "Claron Health International", regionName: "Greater Accra", location: "Airport Residential", contactNumber: "0302771017", email: "wellness@claronhealth.com" },
        { name: "Lapaz Community Hospital", regionName: "Greater Accra", location: "Lapaz", contactNumber: "0302688181/030268817", email: "info@mogcsp.gov.gh" },
        { name: "Grace Anchor Hospital", regionName: "Greater Accra", location: "Nsawam", contactNumber: "0598055595", email: "graceanchormedicalcentre.com" },
        { name: "Bemuah Royal Hospital", regionName: "Greater Accra", location: "East Legon", contactNumber: "0302543652", email: "info@bemuahhospital.com" },
        { name: "Mab International Hospital", regionName: "Greater Accra", location: "Lapaz", contactNumber: "0209494300/054998242", email: "info@mabhospitals.org" },
        { name: "Afrah International Hospital", regionName: "Greater Accra", location: "Asylum Down", contactNumber: "0302267151", email: "afrahinternationalhospital@gmail.com/info@afrahhospital.com" },
        { name: "Tantra Community Hospital", regionName: "Greater Accra", location: "Tantra", contactNumber: "0501395077", email: "tantracommunityclinic@yahoo.com" },
        { name: "Bether Sp. Hospital", regionName: "Greater Accra", location: "Tema", contactNumber: "0302953091", email: "info@bethelspecialisthospital.com" },
        { name: "Ada East District Hospital", regionName: "Greater Accra", location: "Ada", contactNumber: "0244860258", email: "rukymike18@yahoo.com" },
        { name: "Achimota Hospital", regionName: "Greater Accra", location: "Achimota", contactNumber: "0302400212/0302400212", email: "info@achimotahospital.com" },
        { name: "Seventh -Day Adventist Hospital, Gbawe", regionName: "Greater Accra", location: "Accra", contactNumber: "0204412599", email: "sgbawe@yahoo.com/info@gbawesdahospital.com" },
        { name: "New Crystal Hospital", regionName: "Greater Accra", location: "Ashaiman", contactNumber: "0244278434/0303307974", email: "info@newcrystalhealth.org" },
        { name: "New Crystal Hospital", regionName: "Greater Accra", location: "Tema Com 8", contactNumber: "0302977872/0544347239", email: "info@newcrystalhealth.org" },
        { name: "New Crystal Hospital", regionName: "Greater Accra", location: "Afenyo", contactNumber: "0544314384", email: "info@newcrystalhealth.org" },
        { name: "New Crystal Hospital", regionName: "Greater Accra", location: "Adjei kojo", contactNumber: "0544314384", email: "info@newcrystalhealth.org" },
        { name: "Hag Hospital", regionName: "Greater Accra", location: "Greater Accra", contactNumber: "0552617851", email: "care@haghospital.com" },
        { name: "Healthnet", regionName: "Greater Accra", location: "Airport Residential", contactNumber: "0551420412/0508677377", email: "info@healthnet.com" },
        { name: "Accra Medical Centre", regionName: "Greater Accra", location: "Ridge", contactNumber: "0204096099", email: "info@accramed.com" },
        { name: "University of Ghana Medical Center", regionName: "Greater Accra", location: "Legon", contactNumber: "0302550843", email: "info-msrc@ugmc.ug.edu/info-msrc@ugmc.ug.edu.gh" },
        { name: "Nyaho Medical Centre", regionName: "Greater Accra", location: "Airport rsidential", contactNumber: "0501436662", email: "info.ac@yahomedical.com" },
        { name: "Unimed Hospital Limited", regionName: "Greater Accra", location: "Ofankor Barrier", contactNumber: "0303976687", email: "unimedhealth@yahoo.com" },
        { name: "Lena Health Service", regionName: "Greater Accra", location: "Spintex", contactNumber: "0593318165", email: "info@lenashealthcare.org" },
        { name: "Raphal Medical Centre", regionName: "Greater Accra", location: "Dansoman", contactNumber: "0594942166", email: "info@raphalmedicalcentre.com" },
        { name: "Narh-Bita Hospital", regionName: "Greater Accra", location: "Tema Com 4", contactNumber: "0303214905/0303214906", email: "info@narhbita.com" },
        { name: "Istephanie Hospital", regionName: "Greater Accra", location: "Dansoman", contactNumber: "0244320572", email: "info@istephaniehospital.com" },
        { name: "Healthlink Medical Centre", regionName: "Greater Accra", location: "Ashiaman", contactNumber: "0556656455/0592321817", email: "info@healthlinkgh.com" },
        { name: "North Ridge Clinic", regionName: "Greater Accra", location: "Noth ridge", contactNumber: "0203345986", email: "info@northridgeclinic.com" },
        { name: "Acacia Medical Centre", regionName: "Greater Accra", location: "Accra", contactNumber: "0501414015", email: "info@acaciahealthcare.com" },
        { name: "Reviss Maternity & Specialist Clinic", regionName: "Greater Accra", location: "Lakeside,Accra", contactNumber: "0541072063/0504411254", email: "reviss_@yahoo.com" },
        { name: "Acacia Medical Centre", regionName: "Greater Accra", location: "Accra", contactNumber: "0501414015", email: "info@acaciahealthcare.com" },
        { name: "The Trust Hospital & Fertility Centre", regionName: "Greater Accra", location: "Dzorwulu", contactNumber: "0593887685/0302775252", email: "info@thetrusthospital.com" },
        { name: "Bemuah Royal Hospital", regionName: "Greater Accra", location: "North Legon", contactNumber: "0244520178/0501432663", email: "info@bemuahhospital.com" },
        { name: "First Care Hospital", regionName: "Greater Accra", location: "Accra", contactNumber: "0593442732", email: "info@firstcarehospital.com" },
        { name: "New Crystal Health Services", regionName: "Greater Accra", location: "Micheal camp", contactNumber: "0509956000", email: "info@newcrystalhealth.org" },
        { name: "Grace General Hospital", regionName: "Greater Accra", location: "Accra", contactNumber: "0505540054", email: "info@gracegeneralhospital.com" },
        { name: "Valley View Hospital", regionName: "Greater Accra", location: "Oyibi", contactNumber: "0504319694", email: "info@valleyviewhospital.com" },
        { name: "Holy Trinity Medical Centre & Spa", regionName: "Greater Accra", location: "Accra", contactNumber: "0501530004", email: "info@holytrinityhospital.com" },
        { name: "Kelvin Specialist Hospital", regionName: "Greater Accra", location: "Accra", contactNumber: "0596916968", email: "info@kelvinhospital.com" },
        { name: "Lapaz Community Hospital", regionName: "Greater Accra", location: "Accra", contactNumber: "0201234567", email: "info@lapazcommunityhospital.com" },
        { name: "Grace Anchor Hospital", regionName: "Greater Accra", location: "Nsawam", contactNumber: "0598055595", email: "graceanchormedicalcentre.com" },
        { name: "Bemuah Royal Hospital", regionName: "Greater Accra", location: "East Legon", contactNumber: "0302543652", email: "info@bemuahhospital.com" },
        { name: "Mab International Hospital", regionName: "Greater Accra", location: "Lapaz", contactNumber: "0209494300/054998242", email: "info@mabhospitals.org" },
        { name: "Afrah International Hospital", regionName: "Greater Accra", location: "Asylum Down", contactNumber: "0302267151", email: "afrahinternationalhospital@gmail.com/info@afrahhospital.com" },
        { name: "Tantra Community Hospital", regionName: "Greater Accra", location: "Tantra", contactNumber: "0501395077", email: "tantracommunityclinic@yahoo.com" },
        { name: "Bether Sp. Hospital", regionName: "Greater Accra", location: "Tema", contactNumber: "0302953091", email: "info@bethelspecialisthospital.com" },
        { name: "Ada East District Hospital", regionName: "Greater Accra", location: "Ada", contactNumber: "0244860258", email: "rukymike18@yahoo.com" },
        { name: "Achimota Hospital", regionName: "Greater Accra", location: "Achimota", contactNumber: "0302400212/0302400212", email: "info@achimotahospital.com" },
        { name: "Seventh-Day Adventist Hospital, Gbawe", regionName: "Greater Accra", location: "Accra", contactNumber: "0204412599", email: "sgbawe@yahoo.com/info@gbawesdahospital.com" },
        { name: "New Crystal Hospital", regionName: "Greater Accra", location: "Ashaiman", contactNumber: "0244278434/0303307974", email: "info@newcrystalhealth.org" },
        { name: "New Crystal Hospital", regionName: "Greater Accra", location: "Tema Com 8", contactNumber: "0302977872/0544347239", email: "info@newcrystalhealth.org" },
        { name: "New Crystal Hospital", regionName: "Greater Accra", location: "Afenyo", contactNumber: "0544314384", email: "info@newcrystalhealth.org" },
        { name: "New Crystal Hospital", regionName: "Greater Accra", location: "Adjei Kojo", contactNumber: "0544314384", email: "info@newcrystalhealth.org" },
        { name: "Hag Hospital", regionName: "Greater Accra", location: "Greater Accra", contactNumber: "0552617851", email: "care@haghospital.com" },
        { name: "Healthnet", regionName: "Greater Accra", location: "Airport Residential", contactNumber: "0551420412/0508677377", email: "info@healthnet.com" },
        { name: "Accra Medical Centre", regionName: "Greater Accra", location: "Ridge", contactNumber: "0204096099", email: "info@accramed.com" },
        { name: "University of Ghana Medical Center", regionName: "Greater Accra", location: "Legon", contactNumber: "0302550843", email: "info-msrc@ugmc.ug.edu/info-msrc@ugmc.ug.edu.gh" },
        { name: "Nyaho Medical Centre", regionName: "Greater Accra", location: "Airport Residential", contactNumber: "0501436662", email: "info.ac@yahomedical.com" },
        { name: "Unimed Hospital Limited", regionName: "Greater Accra", location: "Ofankor Barrier", contactNumber: "0303976687", email: "unimedhealth@yahoo.com" },
        { name: "Lena Health Service Limited", regionName: "Greater Accra", location: "Accra", contactNumber: "0501583362", email: "info@lenahouseclinic.com" },
        { name: "Synlab", regionName: "Greater Accra", location: "Airport Residential", contactNumber: "0593941609/0501232694", email: "baidengharty@gmail.com" },
        { name: "Quantum Total Wellness Centre", regionName: "Greater Accra", location: "Dansoman", contactNumber: "0558156422/0540620581", email: "eboadu@quantumtotalwellness.com" },
        { name: "New Market Health Centre", regionName: "Greater Accra", location: "Kasoa", contactNumber: "0505568783", email: "info@york.ca" },
        { name: "Sunshine Diagnostic Center", regionName: "Greater Accra", location: "Airport Residential", contactNumber: "0263006653", email: "info@sunshinehealthcareltd@gmail.com" },
        { name: "Halleman Medical Services", regionName: "Greater Accra", location: "Atomic Roundabout", contactNumber: "0556780542/0244733076", email: "" },
        { name: "Euracare", regionName: "Greater Accra", location: "Greater Accra", contactNumber: "0302739390", email: "info@euracare.com.gh" },
        { name: "Nova Wellness Center", regionName: "Greater Accra", location: "Greater Accra", contactNumber: "0269952077", email: "info@novawellnessgh.com" },
        { name: "Global Med Rehab", regionName: "Greater Accra", location: "Kwabenya", contactNumber: "0548438137", email: "globalmedrehab@gmail.com" },
        { name: "Cassi Medical & Diagnostics Centre", regionName: "Greater Accra", location: "Airport", contactNumber: "0308231076", email: "info.cassimedicalanddiagnostics@gmail.com" },
        { name: "Mab Medical Center", regionName: "Greater Accra", location: "Ablekuma", contactNumber: "0302959539", email: "info@mabhospital.org" },
        { name: "Elite Care Medical Centre", regionName: "Greater Accra", location: "East Legon", contactNumber: "0537912291", email: "admin@elitecarecentre.com" },
        { name: "The Diagnostic Centre", regionName: "Greater Accra", location: "East Legon", contactNumber: "0509457991", email: "info@dclgh.com" },
        { name: "Three Mc Ghana Limited", regionName: "Greater Accra", location: "Accra", contactNumber: "0302987133", email: "info@3mcsystems.com" },
        { name: "Best Heart Medical Centre Limited", regionName: "Greater Accra", location: "Amasaman", contactNumber: "0549368489", email: "halidusalam1@gmail.com" },
        { name: "Shepherdcare Medical Centre", regionName: "Greater Accra", location: "Tema", contactNumber: "0307030225", email: "shepherdscaremc@gmail.com" },
        { name: "Ark Medical Centre", regionName: "Greater Accra", location: "Lapaz", contactNumber: "0543236133", email: "arkmedicalgh@gmail.com" },
        { name: "Blue Valley Specialist", regionName: "Greater Accra", location: "Gbawe", contactNumber: "0509461750", email: "bvalleymedical@gmail.com" },
        { name: "Natural Way Herbal Clinic", regionName: "Greater Accra", location: "Kwashieman", contactNumber: "0200792466", email: "naturalwayherbalclinic19@gmail.com" },
        { name: "Rinat Clinic", regionName: "Greater Accra", location: "East Legon", contactNumber: "0302515901", email: "iagbesse@rabitoclinic.com" },
        { name: "Lakeside Clinic", regionName: "Greater Accra", location: "Lakeside", contactNumber: "0302230496", email: "" },
        { name: "Blessings Clinic Ltd", regionName: "Greater Accra", location: "Abeka Road", contactNumber: "0302235696", email: "" },
        { name: "Sandford World Clinic", regionName: "Greater Accra", location: "Adenta", contactNumber: "0302974161", email: "swc@sandfordhealth.org" },
        { name: "Theresa Clinic", regionName: "Greater Accra", location: "Orgle Road", contactNumber: "0244411394", email: "theresasclinic@gmail.com" },
        { name: "Efan Victory Clinic", regionName: "Greater Accra", location: "Batsonaa Highway", contactNumber: "0243229070", email: "efanvictoryclinic2@gmail.com" },
        { name: "Ashaiman Polyclinic", regionName: "Greater Accra", location: "Ashaiman", contactNumber: "0265898684", email: "ashiamanpolyclinic.iv@gmail.com" },
        { name: "Medcare Plus Clinic", regionName: "Greater Accra", location: "Accra", contactNumber: "0264996200", email: "info@medcareplus.ca" },
        { name: "Dansoman Polyclinic", regionName: "Greater Accra", location: "Dansoman", contactNumber: "0205369054/0302304592", email: "dansomanpolyclinic@gmail.com" },
        { name: "Ogbojo Polyclinic", regionName: "Greater Accra", location: "Ogbojo", contactNumber: "0555368374", email: "diana.donkor@ghs.gov.gh" },
        { name: "Anyaa Polyclinic", regionName: "Greater Accra", location: "Anyaa", contactNumber: "0555258123", email: "" },
        { name: "Tema Polyclinic", regionName: "Greater Accra", location: "Tema", contactNumber: "0302944398", email: "" },
        { name: "St. Lukes Clinic", regionName: "Greater Accra", location: "Airport Residential", contactNumber: "0302775405", email: "info@stlukesclinic.com.gh" },
        { name: "Prampram Polyclinic", regionName: "Greater Accra", location: "Prampram", contactNumber: "0303910075/024358462", email: "alexander.balinia-adda@ghs.gov.gh" },
        { name: "Kaneshie Polyclinic", regionName: "Greater Accra", location: "Kaneshie", contactNumber: "0302228288", email: "" },
        { name: "Rabito Clinic", regionName: "Greater Accra", location: "Tema Comm25", contactNumber: "0596914333", email: "info@rabitoclinic.com" },
        { name: "Rabito Clinic", regionName: "Greater Accra", location: "Dansoman", contactNumber: "0596913671", email: "info@rabitoclinic.com" },
        { name: "Rabito Clinic", regionName: "Greater Accra", location: "East Legon", contactNumber: "0592420596", email: "info@rabitoclinic.com" },
        { name: "Rabito Clinic", regionName: "Greater Accra", location: "Kasoa", contactNumber: "0593854713", email: "info@rabitoclinic.com" },
        { name: "Rabito Clinic", regionName: "Greater Accra", location: "Tema C11", contactNumber: "0596913672", email: "info@rabitoclinic.com" },
        { name: "Rabito Clinic", regionName: "Greater Accra", location: "Osu", contactNumber: "0302774526", email: "info@rabitoclinic.com" },
        { name: "Rabito Clinic", regionName: "Greater Accra", location: "Lapaz", contactNumber: "0596913669", email: "info@rabitoclinic.com" },
        { name: "Rabito Clinic", regionName: "Greater Accra", location: "Cosmetic Centre", contactNumber: "0594974375", email: "info@rabitoclinic.com" },
        { name: "Rabito Clinic", regionName: "Greater Accra", location: "Dome", contactNumber: "0593854672", email: "info@rabitoclinic.com" },
        { name: "Rabito Clinic", regionName: "Greater Accra", location: "Kessiman", contactNumber: "0596914321", email: "info@rabitoclinic.com" },
        { name: "Oracare Dental Clinic", regionName: "Greater Accra", location: "Adenta", contactNumber: "0302972742", email: "oracaredentalgh@gmail.com" },
        { name: "Jacob Dental Clinic", regionName: "Greater Accra", location: "East Legon", contactNumber: "0542999699", email: "jacobdental@hotmail.com" },
        { name: "Marks Dental Clinic", regionName: "Greater Accra", location: "Ridge", contactNumber: "0542999699", email: "info@marksdental-clinic.com" },
        { name: "Gilead Medical & Dental Centre", regionName: "Greater Accra", location: "Asylum Down", contactNumber: "0247595950", email: "info@gileadmedgh.com" },
        { name: "Save The Nations Sight Eye Clinic", regionName: "Greater Accra", location: "East Legon", contactNumber: "0207574425", email: "jcibaah@yahoo.com" },
        { name: "Delcielo Optical Services", regionName: "Greater Accra", location: "Ring Road", contactNumber: "0244702542", email: "info@delcielooptical.com" },
        { name: "Innus Eye & Vision Care Centre", regionName: "Greater Accra", location: "Haatso", contactNumber: "0302983354/0243690497", email: "inneseyecare@gmail.com" },
        { name: "My Eyes Center", regionName: "Greater Accra", location: "East Legon", contactNumber: "0262651323", email: "myeyescentre@gmail.com" },
        { name: "Eye Express Limited", regionName: "Greater Accra", location: "Ridge", contactNumber: "0277429279", email: "eye.express@yahoo.com" },
        { name: "Permeff Eye Care", regionName: "Greater Accra", location: "Upsa", contactNumber: "0503261573", email: "permeffeyecare@gmail.com" },
        { name: "Amasha Partners Optical", regionName: "Greater Accra", location: "Spintex", contactNumber: "0244331662", email: "ama.hotor@yahoo.com" },
        { name: "Iris Optometric", regionName: "Greater Accra", location: "Korle Bu Road", contactNumber: "0277671221", email: "hello@iriseyecentre.com" },
        { name: "Third Eye And Vision Centre Limited", regionName: "Greater Accra", location: "Airport Residential/North Ridge", contactNumber: "0245938389", email: "info@thirdeyecare.com" },
        { name: "Emmanuel Eye Centre", regionName: "Greater Accra", location: "East Legon", contactNumber: "0302500578", email: "eemc@lukemissions.org" },
        { name: "Godly Favoured Eye Care Centre", regionName: "Greater Accra", location: "Lapaz", contactNumber: "0535196655", email: "godlyfavored555@gmail.com" },
        { name: "Top Up Pharmacy Limited (Adabraka)", regionName: "Greater Accra", location: "Adabraka", contactNumber: "0242226555", email: "ella10030@gmail.com" },
        { name: "Top Up Pharmacy Limited (Osu)", regionName: "Greater Accra", location: "Osu", contactNumber: "0242226555", email: "ella10030@gmail.com" },
        { name: "Top Up Pharmacy Limited (Airport Residential)", regionName: "Greater Accra", location: "Airport Residential", contactNumber: "0508288478", email: "ella10030@gmail.com" },
        { name: "Top Up Pharmacy Limited (Airport Hills)", regionName: "Greater Accra", location: "Airport Hills", contactNumber: "0506475825", email: "ella10030@gmail.com" },
        { name: "Top Up Pharmacy Limited (East Legon)", regionName: "Greater Accra", location: "East Legon", contactNumber: "0501447384", email: "ella10030@gmail.com" },
        { name: "Add Pharmacy Gh Ltd (Bukum Branch)", regionName: "Greater Accra", location: "Accra", contactNumber: "050157460", email: "info@addpharma4u.com" },
        { name: "Add Pharmacy Gh Ltd (Darkuman Total Branch)", regionName: "Greater Accra", location: "Darkuman", contactNumber: "0501602138", email: "info@addpharma4u.com" },
        { name: "Add Pharmacy (Industrial Area)", regionName: "Greater Accra", location: "Industrial Area", contactNumber: "0501257178", email: "info@addpharma4u.com" },
        { name: "Add Pharmacy (Asylum Down)", regionName: "Greater Accra", location: "Asylum Down", contactNumber: "024717667", email: "info@addpharma4u.com" },
        { name: "Add Pharmacy Gh Ltd (Tse Addo Branch)", regionName: "Greater Accra", location: "Tse Addo", contactNumber: "0501601120", email: "info@addpharma4u.com" },
        { name: "Add Pharmacy Gh Ltd (North Ridge Area)", regionName: "Greater Accra", location: "Ridge", contactNumber: "0244662440", email: "info@addpharma4u.com" },
        { name: "Add Pharmacy Gh Ltd (Pigfarm Total Branch)", regionName: "Greater Accra", location: "Pig Farm", contactNumber: "0501548307", email: "info@addpharma4u.com" },
        { name: "Add Pharmacy Gh Ltd (Movenpick Hotel Branch)", regionName: "Greater Accra", location: "Movenpick", contactNumber: "0266388182", email: "info@addpharma4u.com" },
        { name: "Obm Pharmacy", regionName: "Greater Accra", location: "Tema", contactNumber: "0558233960", email: "obm@newcrystalhealth.org" },
        { name: "Ernest May Chemist", regionName: "Greater Accra", location: "Odorkor", contactNumber: "0303967865", email: "info@ernestchemist.com" },
        { name: "Zoe Pharmacy", regionName: "Greater Accra", location: "Haatso", contactNumber: "0242625998", email: "zoepharmaceuticalslimited@gmail.com" }

    ],
    "Ashanti": [
        { name: "Kuntanase Government Hospital", regionName: "Ashanti", "location": "Kuntanase", "contactNumber": "0547039070", "email": "zellyadjei@gmail.com" },
        { name: "Gary Marvin Memorial Hospital", regionName: "Ashanti", "location": "Kotwi", "contactNumber": "0504386978", "email": "kaffgh031973@gmail.com" },
        { name: "Trinity Health Hospital", regionName: "Ashanti", "location": "Paraku Estate", "contactNumber": "0262315061", "email": "info@holytrinity.com.gh" },
        { name: "Juaso District Hospital", regionName: "Ashanti", "location": "Juaso", "contactNumber": "0244620913", "email": "tiertoore@yahoo.com" },
        { name: "Kokofu General Hospital", regionName: "Ashanti", "location": "Kokofu", "contactNumber": "0244272109", "email": "kokofugh@gmail.com" },
        { name: "Asonomaso Government Hospital", regionName: "Ashanti", "location": "Asonomaso", "contactNumber": "0244264648", "email": "yawggh@yahoo.com" },
        { name: "Adansi North District Hospital", regionName: "Ashanti", "location": "Fomena", "contactNumber": "0246334981", "email": "collins.agyenim@ghs.gov.gh" },
        { name: "True Vine Hospital", regionName: "Ashanti", "location": "Kumasi", "contactNumber": "0549992333", "email": "info@truevinehospitalgh.com" },
        { name: "Akropong Government Hospital", regionName: "Ashanti", "location": "Akropon", "contactNumber": "0243326479", "email": "nicomensah7@gmail.com" },
        { name: "Agona Government Hospital", regionName: "Ashanti", "location": "Agona", "contactNumber": "0247002915", "email": "benjaminekusi@ghs.gov.gh" },
        { name: "Ahafo Ano North Municipal Hospital", regionName: "Ashanti", "location": "Ahafo Ano North", "contactNumber": "0201293503", "email": "tepa.mhar@ghs.gov.gh" },
        { name: "Obuasi Government Hospital", regionName: "Ashanti", "location": "Obuasi", "contactNumber": "0244010801", "email": "mattipeace@yahoo.com" },
        { name: "New Edubiase Government Hospital", regionName: "Ashanti", "location": "New Edubiase", "contactNumber": "0244971631", "email": "princeinowusu@gmail.com" },
        { name: "Mankranso Government Hospital", regionName: "Ashanti", "location": "Tepa Rd,Mankranso", "contactNumber": "0244702588", "email": "swash2007@gmail.com" },
        { name: "Ejura Municipal Hospital", regionName: "Ashanti", "location": "Atebubu-Ejura Rd,Ejura", "contactNumber": "0244251650", "email": "georgeadugyamfi@8mail.com" },
        { name: "Nyinahin Government Hospital A/R", regionName: "Ashanti", "location": "Nyanahin", "contactNumber": "0303959404", "email": "F" },
        { name: "Konongo Hospital", regionName: "Ashanti", "location": "Konongo", "contactNumber": "0592877407", "email": "agyapongsylvester56@gmail.com" },
        { name: "Firstcare Hospital", regionName: "Ashanti", "location": "Anane Avenue", "contactNumber": "0244065422", "email": "info@firstcare.com" },
        { name: "Ausbury Hospital", regionName: "Ashanti", "location": "Anwomaso Rd", "contactNumber": "0540796271", "email": "ausburyhospital@gmail.com" },
        { name: "Afari Community Hospital Limited", regionName: "Ashanti", "location": "Nkawie Rd", "contactNumber": "0240176502", "email": "ach@gmail.com" },
        { name: "A1 Hospital", regionName: "Ashanti", "location": "Bekwai Rd", "contactNumber": "0500941941", "email": "info@a1hospitalsgh.com" },
        { name: "Pima Hospital Limited", regionName: "Ashanti", "location": "Tafo", "contactNumber": "0208162372", "email": "" },
        { name: "St Jude Hospital", regionName: "Ashanti", "location": "Obuasi", "contactNumber": "0262029695", "email": "stjudehospitalobuasi@gmail.com" },
        { name: "Obuasi Ridge Hospital", regionName: "Ashanti", "location": "Obuasi", "contactNumber": "0503484541", "email": "obsridge@gmail.com" },
        { name: "Bryant Mission Hospital", regionName: "Ashanti", "location": "Obuasi", "contactNumber": "0248119813", "email": "" },
        { name: "Tafo Government Hospital", regionName: "Ashanti", "location": "Akyem Kukurantumi", "contactNumber": "0244362927", "email": "tafogovhospitalksi@gmail.com" },
        { name: "Effiduase Government Hospital", regionName: "Ashanti", "location": "Effiduase", "contactNumber": "0240520056F", "email": "eghosp@gmail.com" },
        { name: "Nkawie Toase Govt Hospital", regionName: "Ashanti", "location": "Nkawie Rd, Toase", "contactNumber": "0543108690", "email": "kdetoh@yahoo.com" },
        { name: "Nkenkaasu Government Hospital", regionName: "Ashanti", "location": "Nkenkaasu", "contactNumber": "0546916305", "email": "lewiskarley@yahoo.com" },
        { name: "Mamponteng Hospital", regionName: "Ashanti", "location": "Kumasi", "contactNumber": "0244818303/ 0244174801", "email": "" },
        { name: "Mampong Municipal Hospital", regionName: "Ashanti", "location": "Mampong", "contactNumber": "0243973524", "email": "mampongmunicipalhospital@gmail.com" },
        { name: "Juaben Government Hospital", regionName: "Ashanti", "location": "Juaben", "contactNumber": "0206301924", "email": "" },
        { name: "Ejisu Government Hospital", regionName: "Ashanti", "location": "Ejisu", "contactNumber": "0244596229", "email": "" },
        { name: "Manhyia District Hospital", regionName: "Ashanti", "location": "Zongo Rd,Kumasi", "contactNumber": "0244807070", "email": "info@manhyiahospital-gov.com" },
        { name: "Bekwai Municipal Hospital", regionName: "Ashanti", "location": "Bekwai", "contactNumber": "0245690366/ 057220296", "email": "bekwaimunicipalhospital@yahoo.com" },
        { name: "Sekyedumase Government Hospital", regionName: "Ashanti", "location": "Sekyedumase", "contactNumber": "0244447935", "email": "roacheampong@yahoo.com" },
        { name: "Bechem Government Hospital", regionName: "Ashanti", "location": "Kumasi", "contactNumber": "0247079088", "email": "bechemhospital1950@yahoo.com" },
        { name: "Afari Community Hospital", regionName: "Ashanti", "location": "Nkawie Rd, Kumasi", "contactNumber": "0240176502", "email": "ach@gmail.com" },
        { name: "Obuasi Diagnostic Centre", regionName: "Ashanti", "location": "Obuasi", "contactNumber": "0246074597", "email": "carlosboakye123@gmail.com" },
        { name: "Kodie Hospital", regionName: "Ashanti", "location": "Kodie", "contactNumber": "0200326782", "email": "kenpat@kenpatgroup.com" },
        { name: "Feyiase Baptist Hospital", regionName: "Ashanti", "location": "Kumasi", "contactNumber": "0242396960", "email": "gman2000@yahoo.com" },
        { name: "Akomaa Memorial SDA Hospital", regionName: "Ashanti", "location": "Anomangye", "contactNumber": "0501271150", "email": "info@aims.edu.gh" },
        { name: "Tafo Government Hospital", regionName: "Ashanti", "location": "Akyem Kukurantumi", "contactNumber": "0244362927", "email": "tafogovhospitalksi@gmail.com" },
        { name: "Bechem Government Hospital", regionName: "Ashanti", "location": "Kumasi", "contactNumber": "0247079088", "email": "bechemhospital1950@yahoo.com" },
        { name: "Afari Community Hospital", regionName: "Ashanti", location: "Nkawie Rd, Kumasi", contactNumber: "0240176502", email: "ach@gmail.com" },
        { name: "Obuasi Diagnostic Centre", regionName: "Ashanti", location: "Obuasi", contactNumber: "0246074597", email: "dobuasi@yahoo.com" },
        { name: "Afrancho Health Centre", regionName: "Ashanti", location: "Kumasi", contactNumber: "0277877874", email: "" },
        { name: "Akrofuom Health Centre", regionName: "Ashanti", location: "Amankyim", contactNumber: "0544525453", email: "annorjos2000@yahoo" },
        { name: "Manso Adubia Health Centre", regionName: "Ashanti", location: "Manso, Adubia", contactNumber: "0243662711", email: "" },
        { name: "Akumadan Health Centre", regionName: "Ashanti", location: "Akumadan", contactNumber: "0246322961", email: "" },
        { name: "Brofoyedru Health Centre", regionName: "Ashanti", location: "Brofoyedru, Buoho, Kumasi", contactNumber: "0244725820", email: "oyorteydolo.do@gmail.com" },
        { name: "Beposo Health Centre", regionName: "Ashanti", location: "Beposo", contactNumber: "0208081248/0244245972", email: "beposohealthcentre@yahoo.com" },
        { name: "Adidwan Health Centre", regionName: "Ashanti", location: "Adidwan", contactNumber: "0244181568", email: "" },
        { name: "Asokwa Health Centre", regionName: "Ashanti", location: "Fomena", contactNumber: "0249365525", email: "edjamorla@yahoo.com" },
        { name: "Ayeduase Health Centre", regionName: "Ashanti", location: "Kumasi", contactNumber: "0244239986", email: "" },
        { name: "Offinso Health Centre", regionName: "Ashanti", location: "Sraha", contactNumber: "0243806475", email: "stolazzy@gmail.com" },
        { name: "Government Health Centre Ahenkro", regionName: "Ashanti", location: "Ahenkro", contactNumber: "0200122845", email: "anyomiraph@gmail.com" },
        { name: "Pokukrom Health Centre", regionName: "Ashanti", location: "Fawaman", contactNumber: "0244292684", email: "" },
        { name: "Kwanwoma Health Centre", regionName: "Ashanti", location: "Kumasi", contactNumber: "0572260927", email: "" },
        { name: "Assin Manso Health Centre", regionName: "Ashanti", location: "Assin Manso", contactNumber: "0244132872", email: "" },
        { name: "Aboaso Health Centre", regionName: "Ashanti", location: "Ejura-Kumasi Rd, Aboaso", contactNumber: "0208801472", email: "" },
        { name: "Ahenema Kokoben Health Centre", regionName: "Ashanti", location: "Kumasi", contactNumber: "0243375778", email: "" },
        { name: "Jamasi Health Centre", regionName: "Ashanti", location: "Gyamese", contactNumber: "0245226565", email: "" },
        { name: "Jachie Health Centre", regionName: "Ashanti", location: "Pramso", contactNumber: "0244247534", email: "kwakuboadu@yahoo.com" },
        { name: "Asiwa Health Centre", regionName: "Ashanti", location: "Asiwa", contactNumber: "0277290674/0242370996", email: "" },
        { name: "Prima Medical Centre", regionName: "Ashanti", location: "Kumasi", contactNumber: "0508618903", email: "" },
        { name: "Rabito Clinic", regionName: "Ashanti", location: "Lindador Pharmacy", contactNumber: "0501634173", email: "iagbesse@rabitoclinic.com" },
        { name: "Drobonso RCH Clinic", regionName: "Ashanti", location: "Drabondo", contactNumber: "0242908917", email: "abu.awfo@yahoo.com" },
        { name: "Bomso Clinic", regionName: "Ashanti", location: "Bomso Crescent", contactNumber: "0322496283", email: "iagbesse@rabitoclinic.com" },
        { name: "Rabito Clinic", regionName: "Ashanti", location: "111 Melcom Rd, Kumasi", contactNumber: "244702640", email: "info@rabitoclinic.com" },
        { name: "Manso Nkwanta Polyclinic", regionName: "Ashanti", location: "Manso Nkwanta", contactNumber: "0508450043", email: "kyereboro@gmail.com" },
        { name: "Kumawu Polyclinic", regionName: "Ashanti", location: "Kumawu", contactNumber: "0501336508", email: "skdeoffice@gmail.com" },
        { name: "Abuakwa Polyclinic", regionName: "Ashanti", location: "Kumasi", contactNumber: "0208137761", email: "" },
        { name: "Asuofua Polyclinic", regionName: "Ashanti", location: "Kumasi", contactNumber: "0248735853", email: "" },
        { name: "Quality Health Care", regionName: "Ashanti", location: "Wesleyan Rd", contactNumber: "0277701452", email: "" },
        { name: "Makenzi Health Services", regionName: "Ashanti", location: "Ahinsan Estate", contactNumber: "0571110160/0244460343", email: "" },
        { name: "Briteaid", regionName: "Ashanti", location: "Osei Tutu Ave", contactNumber: "0200111894", email: "info@briteaidhealth.org" },
        { name: "Bandy Chemist", regionName: "Ashanti", location: "Adum Road", contactNumber: "0202110216", email: "" },
        { name: "Saqs Pharmacy", regionName: "Ashanti", location: "Kumasi", contactNumber: "0269123965", email: "saqspharm1@gmail.com" },
        { name: "Greenlight Pharmacy", regionName: "Ashanti", location: "Kumasi", contactNumber: "0538422937", email: "" },
        { name: "Rapheka Pharmacy Limited", regionName: "Ashanti", location: "Kumasi", contactNumber: "0244226160", email: "" },
        { name: "Juliponia Pharmacy", regionName: "Ashanti", location: "Kumasi", contactNumber: "0546795970", email: "" },
        { name: "Estel Pharmacy", regionName: "Ashanti", location: "Akrokerri Rd, Obuasi", contactNumber: "0596912678", email: "oforimensa@gmail.com" },
        { name: "Bandy Chemist", regionName: "Ashanti", location: "Adum-Ashanti", contactNumber: "0202110216", email: "bandychemistenquires@gmail.com" },
        { name: "Bellview Eye Care", regionName: "Ashanti", location: "Obuase", contactNumber: "0322022217", email: "" }

    ],
    "Western": [
        { name: "Prestea Government Hospital", regionName: "Western", location: "Prestea", contactNumber: "0247756333", email: "" },
        { name: "Nana Hima Dekyi Hospital", regionName: "Western", location: "Dixcove", contactNumber: "0248251980", email: "" },
        { name: "Kwesimetwim Government Hospital", regionName: "Western", location: "Takoradi", contactNumber: "0242314754", email: "" },
        { name: "Begoso Government Hospital", regionName: "Western", location: "Prestea", contactNumber: "0249487342", email: "" },
        { name: "Apinto Government Hospital", regionName: "Western", location: "Takoradi", contactNumber: "0243334801", email: "" },
        { name: "Half Asini Government Hospital", regionName: "Western", location: "Asini", contactNumber: "0554085643", email: "samuelkojoasare@gmail.com" },
        { name: "Takoradi Hospital", regionName: "Western", location: "Takoradi", contactNumber: "0246544035", email: "" },
        { name: "Strafford Clinic", regionName: "Western", location: "Takoradi", contactNumber: "0208282611", email: "" },
        { name: "Uretope Eye Care", regionName: "Western", location: "Takoradi", contactNumber: "0205165395", email: "uretopevision@gmail.com" },
        { name: "Adombi Dental", regionName: "Western", location: "Takoradi", contactNumber: "0543341355", email: "oppongkwadwolive@gmail.com" },
        { name: "Oasis Medical Consult", regionName: "Western", location: "Takoradi", contactNumber: "0249129050", email: "info@oasismedicalconsult.com" },
        { name: "A Life Line Medical", regionName: "Western", location: "Shama Rd, Shama", contactNumber: "0246903660", email: "bettyessilfie19@gmail.com" },
        { name: "Benedict Hospital", regionName: "Western", location: "Inchaban, Sekondi-Takoradi", contactNumber: "0246787814", email: "winfkwadwo@yahoo.com" },
        { name: "St Paul Dental Clinic", regionName: "Western", location: "Columbia Ave, Takoradi", contactNumber: "0503346433", email: "selormortho@gmail.com" },
        { name: "Efia Nkwanta Hospital", regionName: "Western", location: "J.De Graft-Johnson Ave, Takoradi", contactNumber: "0209209764", email: "asendark@yahoo.co.uk" },
        { name: "Takoradi High Street Clinic", regionName: "Western", location: "Columbia Ave, Takoradi", contactNumber: "0235559054", email: "thsclinic@ymail.com" },
        { name: "Solar Opticals", regionName: "Western", location: "Stc, Takoradi", contactNumber: "0271638680", email: "solaropticalsltd@yahoo.com" },
        { name: "Delcielo Opticians", regionName: "Western", location: "Liberation Rd, Takoradi", contactNumber: "0246546124", email: "freddisonash@gmail.com" },
        { name: "Abukwa Pharmacy", regionName: "Western", location: "Takoradi", contactNumber: "0244111923", email: "abuakwa.pharmacy@yahoo.com" },
        { name: "Kabmore Pharmacy", regionName: "Western", location: "Takoradi", contactNumber: "0261280160", email: "rexarth49.ra@gmail.com" },
        { name: "Atlantic Chemist", regionName: "Western", location: "Shippers Council Road, Takoradi", contactNumber: "0243688057", email: "aclchemists78@gmail.com" },
        { name: "Qui-Wal Hospital", regionName: "Western", location: "Takoradi", contactNumber: "243411924", email: "" },
        { name: "Nagel Memorial SDA Hospital", regionName: "Western", location: "Takoradi", contactNumber: "0265583293", email: "nagelhospital@gmail.com" },
        { name: "Bethel Methodist Medical Centre", regionName: "Western", location: "5 PakosAve, Takoradi", contactNumber: "0262981771", email: "bmmctadi@gmail.com" },
        { name: "Vision Crafters", regionName: "Western", location: "Harbour Area", contactNumber: "0243529567", email: "vcopticianx@gmail.com" },
        { name: "Imperial Eye Care", regionName: "Western", location: "Takoradi", contactNumber: "0243282775", email: "info@imperialeye.com" },
        { name: "Westview Medical Centre", regionName: "Western", location: "Takoradi", contactNumber: "0209899589", email: "westviewmedicalcentre@gmail.com" },
        { name: "UQ Specialist Medical Services", regionName: "Western", location: "Dial Lane,Takoradi", contactNumber: "0244534553", email: "uQspecialists@ymail.com" },
        { name: "Essikado Hospital", regionName: "Western", location: "Takoradi", contactNumber: "02098089461", email: "" },
        { name: "New Crystal Medical Centre", regionName: "Western", location: "3 Coker Ave, Takoradi", contactNumber: "0312002331", email: "eugeniagyekeadwoa@gmail.com" },
        { name: "Afful Lifeline Med.Centre", regionName: "Western", location: "Shama Rd, Shama", contactNumber: "0548290322", email: "ekuaabuduba@gmail.com" },
        { name: "Agona Nkwanta Polyclinic", regionName: "Western", location: "Ahanta District", contactNumber: "0548638795", email: "deawsome1@gmail.com" },
        { name: "Rabito Clinic", regionName: "Western", location: "Takoradi", contactNumber: "0559740524", email: "iagbesse@rabitoclinic.com" },
        { name: "Takoradi Dis Clinic", regionName: "Western", location: "Takoradi", contactNumber: "0552006666", email: "achimdavid9089@gmail.com" },
        { name: "Twin City Clinic", regionName: "Western", location: "Takoradi", contactNumber: "0312022282", email: "" },
        { name: "Takoradi High Street Clinic", regionName: "Western", location: "Takoradi", contactNumber: "0312023769", email: "" },
        { name: "PH Laboratory Services", regionName: "Western", location: "Fijai, Sekondi-Takoradi", contactNumber: "0255768976", email: "" },
        { name: "Doctors In Service", regionName: "Western", location: "Takoradi", contactNumber: "0579290027", email: "info@doctorsinservice.com" },
        { name: "Solar Eye Center", regionName: "Western", location: "Stc, Takoradi", contactNumber: "0312024832", email: "solaropticalsltd@yahoo.com" },
        { name: "Rapheka Pharmacy", regionName: "Western", location: "Columbia, Takoradi", contactNumber: "0244226160", email: "" },
        { name: "Esikado Hospital", regionName: "Western", location: "Takoradi", contactNumber: "0549052590", email: "" },
        { name: "Oasis Medical Centre", regionName: "Western", location: "Takoradi", contactNumber: "0249129050", email: "info@oasismedicalconsult.com" },
        { name: "St. Benedict Hospital", regionName: "Western", location: "Takoradi", contactNumber: "02445448866", email: "INFO@benedicthospital.com" },
        { name: "Andrews Amihere-Ouarm Vision", regionName: "Western", location: "Takoradi", contactNumber: "0243529567", email: "" },
        { name: "Axim Government Hospital", regionName: "Western", location: "Takoradi", contactNumber: "0559096266", email: "" },
        { name: "Tarwa Old Government Hospital", regionName: "Western", location: "Takoradi", contactNumber: "0243334801", email: "" },
        { name: "Tarwa Municipal Hospital", regionName: "Western", location: "Takoradi", contactNumber: "0246795437", email: "" },
        { name: "Wassa Akropong Government Hospital", regionName: "Western", location: "Takoradi", contactNumber: "0246305405", email: "" }
    ],
    "Central": [
        { name: "Ankaful Leprosy/General Hospital", regionName: "Central", location: "Off-Ankaful Prison Rd", contactNumber: "0244781289", email: "gadanso@yahoo.com" },
        { name: "Adidome Government Hospital", regionName: "Central", location: "Adidome", contactNumber: "0244040158", email: "samadley@yahoo.com" },
        { name: "St. Mary Theresa's Hospital", regionName: "Central", location: "Dodi-Papase", contactNumber: "0501401285", email: "smthdodipapase@chstgh.org" },
        { name: "Cape Coast Metropolitan Hospital", regionName: "Central", location: "Cape Coast", contactNumber: "0244844977/0206558408", email: "adolfolk@yahoo.com" },
        { name: "Gomoa Obuasi Health Centre", regionName: "Central", location: "Afransi", contactNumber: "024470853", email: "millicentkotey09@gmail.com" },
        { name: "Akonfudi Health Centre", regionName: "Central", location: "Assin Akonfudi", contactNumber: "0545463641", email: "george.bempah@gmail.com" },
        { name: "Jukwa Health Centre", regionName: "Central", location: "Jukwa", contactNumber: "0243334633", email: "fishmorefire78@gmail.com" },
        { name: "Abura Dunkwa District Hospital", regionName: "Central", location: "Afransi", contactNumber: "0237707111", email: "martindaiter92@gmail.com" },
        { name: "Bawjiase Polyclinic", regionName: "Central", location: "Awutu Breku", contactNumber: "0245761689", email: "abrantiekomla@gmail.com" },
        { name: "Winneba Manicipal Hospital", regionName: "Central", location: "Winneba", contactNumber: "0244749072", email: "ielzie@gmail.com" },
        { name: "Agona Swedru Municipal Hospital", regionName: "Central", location: "Swedru", contactNumber: "0243884492", email: "trapezium19@gmail.com" },
        { name: "Awutu Health Centre", regionName: "Central", location: "Awutu Breku", contactNumber: "0553066573", email: "rossyksk@gmail.com" },
        { name: "Senya Polyclinic", regionName: "Central", location: "Senya Breku", contactNumber: "0544745587/024270730", email: "copious13@gmail.com" },
        { name: "New Market Health Centre", regionName: "Central", location: "Afransi", contactNumber: "0246372303", email: "mikioteh18@gmail.com" },
        { name: "Assin Fosu Polyclinic", regionName: "Central", location: "Assin Fosu", contactNumber: "0241414239", email: "emmadonkor883@gmail.com" },
        { name: "Assin Manso Health Centre", regionName: "Central", location: "Assin Manso", contactNumber: "0240586202", email: "" },
        { name: "Akoti Health Care", regionName: "Central", location: "Assin Fosu", contactNumber: "0242774026", email: "davidkodua1910@gmail.com" },
        { name: "Sanford World Clinic", regionName: "Central", location: "Sarbah Rd", contactNumber: "0504289235", email: "info@sanfordhealth.org" },
        { name: "Abura Medical Lab", regionName: "Central", location: "Abura Dunkwa", contactNumber: "03321-33967", email: "" },
        { name: "Kingsway Pharmacy", regionName: "Central", location: "Amosima", contactNumber: "0241870001", email: "" },
        { name: "Queens Street Pharmacy", regionName: "Central", location: "Cape Coast", contactNumber: "0244629856", email: "qsprichmond@xtra.co.nz" },
        { name: "Klimovic Medical Centre", regionName: "Central", location: "Windy-Bay Ave", contactNumber: "027-8076221", email: "" },
        { name: "Kleenmed Pharmacy", regionName: "Central", location: "Asante Road, Savoy", contactNumber: "0243-159968", email: "kleenmed.pharm@gmail.com" },
        { name: "Oak Tree Medical", regionName: "Central", location: "Cape Coast", contactNumber: "050-5785086", email: "oaktreemediservices.org" },
        { name: "DIS Clinic", regionName: "Central", location: "Kwamina Walker Ave", contactNumber: "0549441896", email: "info@doctorsinservice.com" },
        { name: "Mankessim Health Centre", regionName: "Central", location: "Mankessim", contactNumber: "244135366", email: "qessiaba@gmail.com" },
        { name: "Awisem Health Centre", regionName: "Central", location: "Assin Fosu", contactNumber: "2450551916", email: "" },
        { name: "Subin Health Center", regionName: "Central", location: "Diaso", contactNumber: "0243773788", email: "" },
        { name: "Breman Asikuma Health Centre", regionName: "Central", location: "Breman Asikuma", contactNumber: "0247731456/0593646915", email: "" },
        { name: "Diaso Health Center", regionName: "Central", location: "Diaso", contactNumber: "02467365541", email: "" },
        { name: "Rabito Clinic", regionName: "Central", location: "Winneba", contactNumber: "0593854713", email: "info@rabitoclinic.com" },
        { name: "Jamra Polyclinic", regionName: "Central", location: "Breman Asikuma", contactNumber: "0553251422/0555210313", email: "" },
        { name: "Twifo Praso Polyclinic", regionName: "Central", location: "Twifo Praso", contactNumber: "209730246", email: "" },
        { name: "Elmina Polyclinic", regionName: "Central", location: "Elmina", contactNumber: "501412294", email: "elimina.pccr@ghs" },
        { name: "Dawurampong Polyclinic", regionName: "Central", location: "Apam", contactNumber: "0245152506", email: "" }
    ],
    "Volta": [
        { name: "Catholic Hospital Battor", regionName: "Volta", location: "Battor", contactNumber: "0242172284", email: "battorcervicalcentre@gmail.com" },
        { name: "Wli Central Health Centre", regionName: "Volta", location: "Likpe Bakwa", contactNumber: "0547737548", email: "" },
        { name: "Volta Municipal Hospital, Hohoe", regionName: "Volta", location: "Hohoe", contactNumber: "0244973608", email: "" },
        { name: "Waya Health Centre", regionName: "Volta", location: "Waya", contactNumber: "0541286121/0244058495", email: "" },
        { name: "Margret Marquart Hospital", regionName: "Volta", location: "Kpando", contactNumber: "362350136", email: "info.mmch1960@gmail.com" },
        { name: "Ziope Health Centre", regionName: "Volta", location: "Ziope", contactNumber: "0247497333", email: "" },
        { name: "Ho Teaching Hospital", regionName: "Volta", location: "Ho-Denu Rd, Ho", contactNumber: "0362027319", email: "info@hth.gov.gh" },
        { name: "Penyi Health Centre", regionName: "Volta", location: "Penyi", contactNumber: "0246201453", email: "melodypenians@gmail.com" },
        { name: "Anfoega Catholic Hospital", regionName: "Volta", location: "818 Derby Ave, Accra", contactNumber: "0501629250", email: "anfoegacatholichospital@yahoo.com" },
        { name: "Juapong Health Centre", regionName: "Volta", location: "Juapong", contactNumber: "0241244170", email: "joycehlodze@gmail.com" },
        { name: "Angola Health Centre", regionName: "Volta", location: "", contactNumber: "0541099999", email: "hpe.kordorwu@ghs.gov.gh" },
        { name: "Tegbi Health Centre", regionName: "Volta", location: "Tegbi", contactNumber: "0243982756", email: "amegahkafui@gmail.com" },
        { name: "Kpando Health Centre", regionName: "Volta", location: "Kpando", contactNumber: "0248803825", email: "" },
        { name: "Kpeve Health Centre", regionName: "Volta", location: "Kpeve", contactNumber: "0246984643", email: "christopher.mbabil@ghs.gov.gh" },
        { name: "Keta Municipal Hospital", regionName: "Volta", location: "Keta", contactNumber: "0554089822", email: "ketahosp@yahoo.com" },
        { name: "Ho Royal Hospital Limited", regionName: "Volta", location: "Ho", contactNumber: "0362095151", email: "royalhospital@yahoo.com" },
        { name: "Ve Golokuati Health Centre", regionName: "Volta", location: "Ve Golokuati", contactNumber: "0246984643", email: "christopher.mbabil@ghs.gov.gh" },
        { name: "Peki Government Hospital", regionName: "Volta", location: "Peki", contactNumber: "0243337943/0245428909", email: "" },
        { name: "Catholic Hospital Battor", regionName: "Volta", location: "Battor", contactNumber: "0246953704", email: "pearl.bedzo@yahoo.com" },
        { name: "Bol Medical Services", regionName: "Volta", location: "Ho", contactNumber: "0244245087", email: "boatengharry988@yahoo.com" },
        { name: "Dzolokpuita Health Centre", regionName: "Volta", location: "Dzolokpuita", contactNumber: "0243166614", email: "" },
        { name: "Dzologbogame Health Centre", regionName: "Volta", location: "Dzologbogame", contactNumber: "0245463170", email: "" },
        { name: "Vakpo Health Centre", regionName: "Volta", location: "Vakpo", contactNumber: "0557785534", email: "" },
        { name: "Fodome Helu Health Centre", regionName: "Volta", location: "Hohoe", contactNumber: "0540822590", email: "" },
        { name: "Cederville Hospital", regionName: "Volta", location: "Hohoe", contactNumber: "0541249464", email: "info@cedarvillehospital.com" },
        { name: "Mary Theresa Hospital", regionName: "Volta", location: "Dodi Papase", contactNumber: "0243268479", email: "" },
        { name: "Foresight Medical Centre", regionName: "Volta", location: "Ho", contactNumber: "0501480982", email: "" },
        { name: "Ho Polyclinic", regionName: "Volta", location: "Ho", contactNumber: "0204277225", email: "konkadaniel@yahoo.com" },
        { name: "Rabito Clinic", regionName: "Volta", location: "Aflao", contactNumber: "0596913667", email: "iagbesse@rabitoclinic.com" }

    ],
    'Bono': [
        { name: "Abrafi Women And Children Hospital", regionName: "Bono", location: "", contactNumber: "0248521014", email: "yeboahdavid85@yahoo.com" },
        { name: "Greenlight Pharmacy", regionName: "Bono", location: "", contactNumber: "0209944881", email: "" },
        { name: "Nsoatre Polyclinic", regionName: "Bono", location: "", contactNumber: "0554124547", email: "joeeesh79@yahoo.com" },
        { name: "Dormaa West District Hospital", regionName: "Bono", location: "Nkrankwanta", contactNumber: "0243721481/0555146588", email: "dwdhosp2019@yahoo.com" },
        { name: "Dormaa East District Hospital", regionName: "Bono", location: "Wamfie", contactNumber: "0243182449", email: "mamekwenuba@gmil.com" },
        { name: "Jinijini Health Centre", regionName: "Bono", location: "Jinjini", contactNumber: "0200804325", email: "richmonddwaase@gmail.com" },
        { name: "Drobo Polyclinic", regionName: "Bono", location: "Drobo", contactNumber: "024272760", email: "barimah41@gmail.com" },
        { name: "Sampa Government Hospital", regionName: "Bono", location: "Sampa", contactNumber: "0249321069", email: "theresa.botchway@yahoo.com" },
        { name: "Banda Nhenkro Health Centre", regionName: "Bono", location: "Banda Nhenkro", contactNumber: "0240463851", email: "" },
        { name: "Tain District Hospital Nsawkaw", regionName: "Bono", location: "Nsawkaw", contactNumber: "0245115888", email: "richardasamoah200@gmail.com" },
        { name: "Wenchi Health Centre", regionName: "Bono", location: "Wenchi", contactNumber: "0554557876", email: "" },
        { name: "Sena West District Hospital", regionName: "Bono East", location: "Sena West", contactNumber: "0240514872", email: "osmanabakere@gmail.com" },
        { name: "Municipal Hospital Atebubu", regionName: "Bono East", location: "Atebubu", contactNumber: "0245953472", email: "alhassan.mohammud936@gmail.com" },
        { name: "Prang Health Centre", regionName: "Bono East", location: "Prang", contactNumber: "0547512743", email: "vidakunkuri@gmail.com" },
        { name: "Busunya Polyclinic", regionName: "Bono East", location: "Busunya", contactNumber: "0553514937", email: "buckmanebenezer6@gmail.com" },
        { name: "Nkoranza Health Centre", regionName: "Bono East", location: "Nkoranza", contactNumber: "0242856541", email: "nketiaduncan@gmail.com" },
        { name: "Kintampo Municipal Hospital", regionName: "Bono East", location: "Kintampo", contactNumber: "0244972355", email: "isswud@gmail.com" },
        { name: "Kintampo South District Hospital", regionName: "Bono East", location: "Kintampo", contactNumber: "0265603426", email: "mossay1970@gmail.com" },
        { name: "Tuobodom Health Centre", regionName: "Bono East", location: "Tuobodom", contactNumber: "0543313402", email: "adjeibanchaglahf45@gmail.com" },
        { name: "Kwatire Hospital", regionName: "Bono", location: "Odumasi", contactNumber: "0243739577", email: "ofori0247752906@gmail.com" },
        { name: "Nsoatre Polyclinic", regionName: "Bono", location: "Odumasi", contactNumber: "0501384251", email: "princeagyemang75@gmail.com" },
        { name: "Sunyani Municipal Hospital", regionName: "Bono", location: "Sunyani", contactNumber: "0244934873", email: "" },
        { name: "Health Point Hospital", regionName: "Bono", location: "", contactNumber: "0302798221", email: "" },
        { name: "Bono Regional Hospital", regionName: "Bono", location: "Sunyani", contactNumber: "0546388343", email: "" },
        { name: "Chiraa Hospital", regionName: "Bono", location: "Chiraa", contactNumber: "0242459569", email: "kumifrimpongderek@yahoo.com" },
        { name: "Fiappe Health Centre", regionName: "Bono", location: "Odumasi", contactNumber: "0244866056", email: "" },
        { name: "Worae Care Clinic", regionName: "Bono", location: "", contactNumber: "0302781258", email: "" },

    ],
    "Ahafo": [
        { name: "Techimantia Government Hospital", regionName: "Ahafo", location: "Techiman", contactNumber: "0208147381/0352122121", email: "" },
        { name: "Bibiani Municipal Hospital", regionName: "Ahafo", location: "Bibiani", contactNumber: "0243334801", email: "municipalhospital108bibiani@gmail.com" },
        { name: "Kukuom District Hospital", regionName: "Ahafo", location: "Asunafo South District", contactNumber: "0242740272", email: "" },
        { name: "Goaso Municipal Government Hospital", regionName: "Ahafo", location: "Goase", contactNumber: "0244929314", email: "ankomah28@gmail.com" },
        { name: "St Elizabeth Catholic Hospital", regionName: "Ahafo", location: "Hwidiem", contactNumber: "0322298428", email: "info@sech-gh.org" },
        { name: "Kenyasi District Hospital", regionName: "Ahafo", location: "Asutifi North", contactNumber: "0545183001", email: "bonyinobed@gmail.com" },
        { name: "Banhart Hospital", regionName: "Ahafo", location: "Asutifi North", contactNumber: "0244602792", email: "" },
        { name: "Bechem Government Hospital", regionName: "Ahafo", location: "Sunyani", contactNumber: "0247079088", email: "bechemhospital1950@yahoo.com" },
        { name: "Asunafo South District Hospital, Kukuom", regionName: "Ahafo", location: "Kukuom", contactNumber: "0546291969", email: "josephtey20@gmail.com" },
        { name: "Holy Family Hospital", regionName: "Ahafo", location: "Techiman-Tamale Road, Techiman", contactNumber: "0544353020", email: "hfhnkawkaw@chstgh.org" },
        { name: "Abrafi Women And Children Hospital", regionName: "Ahafo", location: "AN1 Nana Dwamena St, Techiman", contactNumber: "0248521014", email: "fadlequantson@gmail.com" },
        { name: "Nsoatre Health Centre", regionName: "Ahafo", location: "Nsuatre", contactNumber: "0554124547", email: "joeeesh79@yahoo.com" },
        { name: "Mim Health Center", regionName: "Ahafo", location: "Mim", contactNumber: "0207446162", email: "mazzymartin97@gmail.com" },
        { name: "Aspire Clinic and Maternity Home", regionName: "Ahafo", location: "Sunyani", contactNumber: "0542500793", email: "" },
        { name: "Divine Star Clinic and Maternity", regionName: "Ahafo", location: "", contactNumber: "0303967440", email: "" },
        { name: "Rabito Clinic", regionName: "Ahafo", location: "Sunyani", contactNumber: "02093028008/0244974669", email: "info@rabitoclinic.com" },
        { name: "Chiraa", regionName: "Ahafo", location: "Sunyani", contactNumber: "0352196718", email: "" },
        { name: "Medcourt Pharmacy", regionName: "Ahafo", location: "Bechem", contactNumber: "0244464025/0505004915", email: "info@medcourtpharmacyltd.com" },
        { name: "Alma Medical", regionName: "Ahafo", location: "Sunyani", contactNumber: "0243680058", email: "" },
        { name: "St. John of God Catholic Hospital", regionName: "Ahafo", location: "Tano North", contactNumber: "0243823009", email: "" },
        { name: "Bomaa Government Hospital", regionName: "Ahafo", location: "Tano North", contactNumber: "0243354856", email: "" }

    ],
    "Eastern": [
        { name: "Kade Government Hospital", regionName: "Eastern", location: "Kade", contactNumber: "0508321413", email: "kade.gher@ghs.gov.gh" },
        { name: "St John Catholic Polyclinic, Akim Ofoase", regionName: "Eastern", location: "West Akim Municipal", contactNumber: "0249990902", email: "delsturbo@yahoo.com" },
        { name: "Sda Hospital, Koforidua", regionName: "Eastern", location: "Koforidua", contactNumber: "0541369379", email: "larbicompson@gmail.com" },
        { name: "Divine Victory Hospital", regionName: "Eastern", location: "West Akim Municipal", contactNumber: "0244155101", email: "isaacfialor@gmail.com" },
        { name: "Atua Government Hospital", regionName: "Eastern", location: "Lower Manya Krobo Municipal", contactNumber: "0247126996", email: "tamakloevincent100@yahoo.com" },
        { name: "Yilo Krobo Hospital", regionName: "Eastern", location: "Yilo Krobo Municipal", contactNumber: "0244459757", email: "ekashiabi@gmail.com" },
        { name: "Kibi Government Hospital", regionName: "Eastern", location: "Upper West Akim District", contactNumber: "0241394588", email: "popomicheal66@gmail.com" },
        { name: "Enyiresi Government Hospital", regionName: "Eastern", location: "Akyem, Enyiresi", contactNumber: "0549119192", email: "drebenamo@gmail.com" },
        { name: "Presbyterian Hospital, Donkokrom", regionName: "Eastern", location: "Donkokrom", contactNumber: "0249735012", email: "effahaugustine25@gmail.com" },
        { name: "Cato Clinic Ltd", regionName: "Eastern", location: "New Juaben North Municipal", contactNumber: "0247572760", email: "dicksonkboakye@gmail.com" },
        { name: "New Abirem Government Hospital", regionName: "Eastern", location: "Birim Central Municipal", contactNumber: "0244225832", email: "kwekuabu@gmail.com" },
        { name: "Oda Government Hospital", regionName: "Eastern", location: "Koforidua", contactNumber: "0541285991", email: "odagovernmenthospital@yahoo.com" },
        { name: "Nsawam Government Hospital", regionName: "Eastern", location: "Nsawam", contactNumber: "541116563", email: "nsawamgovernmenthospital@gmail.com" },
        { name: "Divine Victory Hospital", regionName: "Eastern", location: "Akim, Oda", contactNumber: "0244155101/0202171044", email: "divinevictory@gmail.com" },
        { name: "Kenop Hospital Care", regionName: "Eastern", location: "Nkwakaw", contactNumber: "03033939579/0243038761/054244580", email: "kenopcarehospital@yahoo.com" },
        { name: "Asamankese Government Hospital", regionName: "Eastern", location: "Asamankese", contactNumber: "0342091049", email: "" },
        { name: "Holy Family Hospital", regionName: "Eastern", location: "Nkwakaw", contactNumber: "544353020", email: "hfhnkawkaw@chstgh.org" },
        { name: "Eastern Regional Hospital", regionName: "Eastern", location: "Koforidua", contactNumber: "0243251680", email: "samadzadi@gmail.com" },
        { name: "St. Johns Hospital And Fertility Centre", regionName: "Eastern", location: "Nsawam", contactNumber: "0501258518", email: "info@stjohnshfc.com" },
        { name: "Newlands Medical Centre", regionName: "Eastern", location: "Koforidua", contactNumber: "0261218459", email: "nelandsmedicalcentre@gmail.com" },
        { name: "Rabito Clinic", regionName: "Eastern", location: "Koforidua", contactNumber: "0559740544", email: "info@rabitoclinic.com" },
        { name: "Catholic Community & Maternity Clinic", regionName: "Eastern", location: "Akim, Swedru", contactNumber: "0302518428/0272202288", email: "ccmakimswedru@chstgh.org" },
        { name: "St. John Polyclinic", regionName: "Eastern", location: "Akim Ofoase", contactNumber: "0545152629", email: "sjpakimofoase@chstgh.org" },
        { name: "Tetteth Quarshie Memorial Hospital", regionName: "Eastern", location: "Mampong", contactNumber: "0501580029", email: "tgmhma61@gmail.com" },
    ],
    "Oti": [
        { name: "Bonakye Health Centre", regionName: "Oti", location: "Nkwanta South Municipal", contactNumber: "0241818985", email: "stanleytornyo@gmail.com" },
        { name: "Nyambong Chps Zone", regionName: "Oti", location: "Nkwanta South Municipal", contactNumber: "0245598564", email: "" },
        { name: "Brewaniase Health Center", regionName: "Oti", location: "Nkwanta North District", contactNumber: "0249454126", email: "faustinaquayson@gmail.com" },
        { name: "Krachi West Municipal Hospital", regionName: "Oti", location: "Krachi West District", contactNumber: "0547776579", email: "raphealtumuwa@gmail.com" },
        { name: "Worawora Government Hospital", regionName: "Oti", location: "Nkwanta North District", contactNumber: "0243154192", email: "ahetebright@yahoo.com" },
        { name: "Kpassa Health Centre", regionName: "Oti", location: "Nkwanta North District", contactNumber: "0547676441", email: "yahaya.yabara@ghs.gov.gh" },
        { name: "Abotoase Health Centre", regionName: "Oti", location: "Jasikan District", contactNumber: "0246786138", email: "gnuworkpor@gmail.com" },
        { name: "Likpe Polyclinic", regionName: "Oti", location: "Krachi East Municipal", contactNumber: "0540609003", email: "gershon.gesu@ghs.gov.gh" },
        { name: "Katanga Health Centre", regionName: "Oti", location: "Katanga", contactNumber: "0247497888", email: "oparebeahasiedu@yahoo.com" },
        { name: "Comfort Ofedie Memorial Health Centre", regionName: "Oti", location: "Nkonya Ahenkro", contactNumber: "0246786138", email: "gnuworkpor@gmail.com" },
        { name: "Kpessa Health Centre", regionName: "Oti", location: "Nkwanta", contactNumber: "0547676441", email: "yahaya.yabara@ghs.gov.gh" },
        { name: "Dodo Amafrom Health Centre", regionName: "Oti", location: "Kadjebi", contactNumber: "0245493199", email: "bsekorme@gmail.com" },
        { name: "Dambai Health Centre", regionName: "Oti", location: "Krachi East Municipal", contactNumber: "0240262069", email: "solomonamoah291@gmail.com" },
        { name: "Nkwanta South Municipal Hospital", regionName: "Oti", location: "Nkwanta", contactNumber: "0244884356", email: "" },
        { name: "Chinderi Health Centre", regionName: "Oti", location: "Kyinderi", contactNumber: "246521124", email: "amosbatsa75@gmail.com" },
        { name: "Kadjebi Health Centre", regionName: "Oti", location: "Kadjebi", contactNumber: "0242551037/0246706204", email: "" },
        { name: "St. Lukes Clinic", regionName: "Oti", location: "Kyinderi", contactNumber: "0249630123", email: "info@stlukesclinic.com.gh" }
    ],
    "Northern": [
        { name: "Tolon District Hospital", regionName: "Northern", location: "Tolon District", contactNumber: "0243528090", email: "tolonhospital@gmail.com" },
        { name: "Kpandai District Hospital", regionName: "Northern", location: "Kpandai District", contactNumber: "0243732873", email: "mahal2003@yahoo.com" },
        { name: "Nanton Health Centre", regionName: "Northern", location: "Nanton District", contactNumber: "0244970567", email: "nantondha@gmail.com" },
        { name: "Tamale West Hospital", regionName: "Northern", location: "Tamale Metropolitan", contactNumber: "0242362695", email: "armohammed001@gmail.com" },
        { name: "Choggu Health Centre", regionName: "Northern", location: "Sagnarigu Municipal", contactNumber: "0242211553", email: "napoliondon@gmail.com" },
        { name: "Karaga District Hospital", regionName: "Northern", location: "Karaga District", contactNumber: "0244789790", email: "tiyuuniba@yahoo.com" },
        { name: "Tatale District Hospital", regionName: "Northern", location: "Tatale/Sanguli District", contactNumber: "0246968070", email: "samsonadjei75@yahoo.com" },
        { name: "Sang Health Centre", regionName: "Northern", location: "Tatale/Sanguli District", contactNumber: "0246655427", email: "dakoriviela1980@gmail.com" },
        { name: "Saboba Health Centre", regionName: "Northern", location: "Saboba District", contactNumber: "0244987111", email: "haukiss@yahoo.com" },
        { name: "Kumbungu Health Centre", regionName: "Northern", location: "Kumbungu District", contactNumber: "0245988548", email: "morojutta@gmail.com" },
        { name: "Zamzugu District Hospital", regionName: "Northern", location: "Tatale/Sanguli District", contactNumber: "0243877277", email: "sakomeh1@yahoo.com" },
        { name: "Northern Regional Hospital", regionName: "Northern", location: "Tamale Metropolitan", contactNumber: "0244766565", email: "tengfahalice@gmail.com" },
        { name: "Yendi Municipal Hospital", regionName: "Northern", location: "Yendi Municipal", contactNumber: "0243118643", email: "yendihospital@gmail.com" },
        { name: "Bimbimla Municipal Hospital", regionName: "Northern", location: "Nanumba North Municipal", contactNumber: "0247913176", email: "gbadamahama@yahoo.com" },
        { name: "Gushegu Municipal Hospital", regionName: "Northern", location: "Gushegu Municipal", contactNumber: "02042001834", email: "gushegumunicipalhospital@gmail.com" },
        { name: "Tamale SDA Hospital", regionName: "Northern", location: "Salaga Rd, Tamale", contactNumber: "0372022073", email: "sdatamhosp@yahoo.com" },
        { name: "Tamale Teaching Hospital", regionName: "Northern", location: "Tamale", contactNumber: "0372000180", email: "info@tth.gov.gh" },
        { name: "Tatale District Hospital", regionName: "Northern", location: "Tamale", contactNumber: "0372000180", email: "info@tth.gov.gh" },
        { name: "Rabito Clinic", regionName: "Northern", location: "Tamale", contactNumber: "0543115557", email: "info@rabitoclinic.com" }
    ],
    "Upper West": [
        { name: "Nadowli District Hospital", regionName: "Upper West", location: "Wa", contactNumber: "0200215251/0549297000", email: "o.Inusah@yahoo.com" },
        { name: "Tumu Municipal Hospital", regionName: "Upper West", location: "Tumu", contactNumber: "0242952279/0502649555", email: "adnanab14@yahoo.com" },
        { name: "Lambussie Policlinic", regionName: "Upper West", location: "Lambussie", contactNumber: "0208184463", email: "sarpongalexa96@gmail.com" },
        { name: "Hain Policlinic", regionName: "Upper West", location: "Hain", contactNumber: "0248205314", email: "abdulaziz40@gmail.com" },
        { name: "Funsi Health Centre", regionName: "Upper West", location: "Funsi", contactNumber: "0247215504", email: "likpiakibjamesbikilaati@gmail.com" },
        { name: "Upper West Regional Hospital", regionName: "Upper West", location: "Wa", contactNumber: "0559481052", email: "fluguniah@yahoo.com" },
        { name: "Nandom Health Centre", regionName: "Upper West", location: "Tanoso", contactNumber: "0244140644", email: "fallenoma@gmail.com" },
        { name: "Rabito Clinic", regionName: "Upper West", location: "Wa", contactNumber: "302774526", email: "info@rabitoclinic.com" },
        { name: "Nalerigu College of Health", regionName: "Upper West", location: "Nalerigu", contactNumber: "0247072678", email: "seidusalam53@gmail.com" },
        { name: "Jirapa Urban Health", regionName: "Upper West", location: "Jirapa", contactNumber: "0544487531", email: "empengyeng@gmail.com" },
        { name: "Lawra Municipal Hospital", regionName: "Upper West", location: "Lawra", contactNumber: "0248940333/0248490367", email: "" },
        { name: "Sissala West Municipal Hospital", regionName: "Upper West", location: "Gwolu", contactNumber: "024038073", email: "" }
    ],
    "Upper East": [
        { name: 'Rabito Clinic', regionName: "Upper West", location: "Tempane", contactNumber: "0559740553", email: "info@rabitoclinic.com" },
    ],
    "Savannah": [
        { name: "Daboya Health Centre", regionName: "Savannah", location: "Damongo", contactNumber: "0542096080", email: "ayimaduemmanuel16@gmail.com" },
        { name: "Buipe Health Centre", regionName: "Savannah", location: "N10, Buipe", contactNumber: "0243461219", email: "buipepolyclinic123@gmail.com" },
        { name: "Bole District Hospital", regionName: "Savannah", location: "Bole", contactNumber: "0205559021", email: "mohammedawalabdallah03@gmail.com" },
        { name: "Salaga Municipal Hospital", regionName: "Savannah", location: "Salaga", contactNumber: "0243183885", email: "" },
        { name: "Sawla Tuna Kalba District Hospital", regionName: "Savannah", location: "Sawla", contactNumber: "0243958059", email: "akpeafaa@gmail.com" },
        { name: "Damongo Health Centre", regionName: "Savannah", location: "Damango", contactNumber: "0243448794", email: "abdulganiyunuhu5@gmail.com" }
    ],
    "North East": [
        { name: "Walewale Municipal Hospital", regionName: "North East", location: "Walewale", contactNumber: "0596492224", email: "slouknaan@yahoo.com" },
        { name: "Nasuan Health Centre", regionName: "North East", location: "Nasuan", contactNumber: "0242205337", email: "ballahmusah@gmail.com" },
        { name: "Nalerigu College Of Health, Health Centre", regionName: "North East", location: "Nalerigu", contactNumber: "0247072678", email: "seidusalam53@gmail.com" },
        { name: "Binde Hospital", regionName: "North East", location: "Bende", contactNumber: "0244298735", email: "susanasign72@gmail.com" },
        { name: "Wa West District Hospital", regionName: "North East", location: "Wa", contactNumber: "0243786735", email: "jadongo@ymail.com" },
        { name: "Chereponi District Hospital", regionName: "North East", location: "Chereponi", contactNumber: "0243507575", email: "emmakanto4u@gmail.com" },
        { name: "Yunyoo Health Centre", regionName: "North East", location: "Yunyoo Nasuan", contactNumber: "0540715344", email: "ballahmusah@gmail.com" },
        { name: "Kuburi Polyclinic", regionName: "North East", location: "", contactNumber: "0242064000", email: "rafsaleman@gmail.com" },
        { name: "Yagaba Health Centre", regionName: "North East", location: "Yagaba", contactNumber: "0208256757", email: "rafsuleman@gmail.com" },
        { name: "Janga Hospital", regionName: "North East", location: "Janga", contactNumber: "0540833587", email: "valerialolig7@gmail.com" },
        { name: "Rabito Clinic", regionName: "North East", location: "Wa", contactNumber: "0502538689", email: "" }
    ],
    "Western North": [
        { name: "Essam Government Hospital", regionName: "Western North", location: "Debiso", contactNumber: "0553040973", email: "benebuah5@gmail.com" },
        { name: "Dadeiso Government Hospital", regionName: "Western North", location: "Dedeiso", contactNumber: "0243819702", email: "sethkwame1977@yahoo.com" },
        { name: "Enchi Government Hospital", regionName: "Western North", location: "Enchi", contactNumber: "0546291705", email: "bernamen2010@yahoo.com" }
    ],

}
